type \dev\corn\language.phr          >  \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\cropsyst.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\cropfile.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\crop.phr                    >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\chem.phr                    >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\et.phr                      >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\erosion.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\fmtfile.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\mgmtfile.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\nitrogen.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\residue.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\simfile.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\project.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\scenario.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\soilfile.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\soil.phr                    >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\rptoptns.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\cs_chem.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\cs_crops.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\cs_rprt.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\cs_till.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\phensync.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\validate.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\watertab.phr                >> \cs_suite\cropsyst\phrasesc.lng
REM type params.phr              >> \cs_suite\cropsyst\phrasesc.lng
type \dev\corn\datetime\date.phr              >> \cs_suite\cropsyst\phrasesc.lng
type \dev\corn\validtyp.phr          >> \cs_suite\cropsyst\phrasesc.lng
type \dev\corn\units.phr             >> \cs_suite\cropsyst\phrasesc.lng
type \dev\corn\rui\datereq.phr       >> \cs_suite\cropsyst\phrasesc.lng
type \dev\common\units.phr    >> \cs_suite\cropsyst\phrasesc.lng
type \dev\common\measure\units.phr    >> \cs_suite\cropsyst\phrasesc.lng
type \dev\common\weather\units.phr    >> \cs_suite\cropsyst\phrasesc.lng
type \dev\common\soil\scs\scs.phr      >> \cs_suite\cropsyst\phrasesc.lng
type \dev\common\weather\locfile.phr  >> \cs_suite\cropsyst\phrasesc.lng
type \dev\common\weather\wthrfile.phr >> \cs_suite\cropsyst\phrasesc.lng
type \dev\common\weather\weather.phr  >> \cs_suite\cropsyst\phrasesc.lng
type \dev\common\soil\texttri.phr  >> \cs_suite\cropsyst\phrasesc.lng
REM The following are for the main model only
type \dev\cropsyst\phrases\cs_event.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\cs_grow.phr                  >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\cs_rslts.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\cs_soils.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\events.phr                   >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\csc.phr                      >> \cs_suite\cropsyst\phrasesc.lng

REM The following are for the parameter editor
type \dev\corn\rui\formdlg.phr           >> \cs_suite\cropsyst\phrasesc.lng
type \dev\corn\rui\filedlg.phr           >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\tilsldlg.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\mgmtdlg.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\optdlg.phr                 >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\smrotdlg.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\slprfdlg.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\fmtdlg.phr                  >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\csbdlg.phr                  >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\smctldlg.phr                >> \cs_suite\cropsyst\phrasesc.lng
type \dev\cropsyst\phrases\arccs.phr                   >> \cs_suite\cropsyst\phrasesc.lng

REM GOTO temp_disabled
REM Now make .ph and .pc files for not using translator class
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\cropsyst.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\cropfile.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\crop.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\chem.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\et.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\erosion.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\fmtfile.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\mgmtfile.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\nitrogen.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\residue.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\simfile.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\project.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\scenario.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\soilfile.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\soil.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\rptoptns.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\cs_chem.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\cs_crops.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\cs_grow.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\cs_rprt.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\cs_till.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\cs_event.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\csc.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\phensync.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\validate.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\watertab.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\cs_rslts.phr
REM \dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\params.phr
REM \dev\corn\utilities\phr2ph  \dev\corn\date.phr
\dev\corn\utilities\phr2ph  \dev\corn\rui\datereq.phr
\dev\corn\utilities\phr2ph  \dev\corn\validtyp.phr
\dev\corn\utilities\phr2ph  \dev\corn\units.phr
REM \dev\corn\utilities\phr2ph  \dev\common\units.phr
\dev\corn\utilities\phr2ph  \dev\common\measure\units.phr
\dev\corn\utilities\phr2ph  \dev\common\weather\units.phr
\dev\corn\utilities\phr2ph  \dev\common\soil\scs\scs.phr
\dev\corn\utilities\phr2ph  \dev\common\weather\locfile.phr
\dev\corn\utilities\phr2ph  \dev\common\weather\wthrfile.phr
\dev\corn\utilities\phr2ph  \dev\common\weather\weather.phr
\dev\corn\utilities\phr2ph  \dev\common\soil\texttri.phr
REM The following are for the parameter editor
\dev\corn\utilities\phr2ph  \dev\corn\rui\formdlg.phr
\dev\corn\utilities\phr2ph  \dev\corn\rui\filedlg.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\tilsldlg.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\mgmtdlg.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\optdlg.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\smrotdlg.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\slprfdlg.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\fmtdlg.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\csbdlg.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\smctldlg.phr
\dev\corn\utilities\phr2ph  \dev\cropsyst\phrases\arccs.phr

REM Now make the english only  phrases strings



type \dev\cropsyst\phrases\cropsyst.pcs  > static_phrases.cpp
type \dev\cropsyst\phrases\cropfile.pcs  >> static_phrases.cpp
type \dev\cropsyst\phrases\crop.pcs      >> static_phrases.cpp
type \dev\cropsyst\phrases\chem.pcs      >> static_phrases.cpp
type \dev\cropsyst\phrases\et.pcs        >> static_phrases.cpp
type \dev\cropsyst\phrases\erosion.pcs   >> static_phrases.cpp
type \dev\cropsyst\phrases\fmtfile.pcs   >> static_phrases.cpp
type \dev\cropsyst\phrases\mgmtfile.pcs  >> static_phrases.cpp
type \dev\cropsyst\phrases\nitrogen.pcs  >> static_phrases.cpp
type \dev\cropsyst\phrases\residue.pcs   >> static_phrases.cpp
type \dev\cropsyst\phrases\simfile.pcs   >> static_phrases.cpp
type \dev\cropsyst\phrases\project.pcs   >> static_phrases.cpp
type \dev\cropsyst\phrases\scenario.pcs   >> static_phrases.cpp
type \dev\cropsyst\phrases\soilfile.pcs  >> static_phrases.cpp
type \dev\cropsyst\phrases\soil.pcs      >> static_phrases.cpp
type \dev\cropsyst\phrases\rptoptns.pcs  >> static_phrases.cpp
type \dev\cropsyst\phrases\cs_chem.pcs   >> static_phrases.cpp
type \dev\cropsyst\phrases\cs_crops.pcs  >> static_phrases.cpp
type \dev\cropsyst\phrases\cs_grow.pcs  >> static_phrases.cpp
type \dev\cropsyst\phrases\cs_rprt.pcs   >> static_phrases.cpp
type \dev\cropsyst\phrases\cs_till.pcs   >> static_phrases.cpp
type \dev\cropsyst\phrases\cs_event.pcs   >> static_phrases.cpp
type \dev\cropsyst\phrases\csc.pcs   >> static_phrases.cpp
type \dev\cropsyst\phrases\phensync.pcs  >> static_phrases.cpp
type \dev\cropsyst\phrases\validate.pcs  >> static_phrases.cpp
type \dev\cropsyst\phrases\watertab.pcs  >> static_phrases.cpp
type \dev\cropsyst\phrases\cs_rslts.pcs  >> static_phrases.cpp
REM type \dev\cropsyst\phrases\params.pcs               >> static_phrases.cpp
type \dev\corn\datetime\date.pcs               >> static_phrases.cpp
REM date.pc will be hand done in some cases????
REM type \dev\corn\validtyp.pcs           >> static_phrases.cpp  This will be hand done
type \dev\corn\units.pcs              >> static_phrases.cpp
type \dev\common\units.pcs     >> static_phrases.cpp
type \dev\common\weather\units.pcs     >> static_phrases.cpp
type \dev\common\measure\units.pcs     >> static_phrases.cpp
type \dev\common\soil\scs\scs.pcs       >> static_phrases.cpp
type \dev\common\weather\locfile.pcs   >> static_phrases.cpp
type \dev\common\weather\wthrfile.pcs  >> static_phrases.cpp
type \dev\common\weather\weather.pcs   >> static_phrases.cpp
type \dev\common\soil\texttri.pcs   >> static_phrases.cpp
REM The following are for the parameter editor
type \dev\corn\rui\formdlg.pcs            >> static_phrases.cpp
type \dev\corn\rui\filedlg.pcs            >> static_phrases.cpp
type \dev\cropsyst\phrases\tilsldlg.pcs                 >> static_phrases.cpp
type \dev\cropsyst\phrases\mgmtdlg.pcs                  >> static_phrases.cpp
type \dev\cropsyst\phrases\optdlg.pcs                   >> static_phrases.cpp
type \dev\cropsyst\phrases\smrotdlg.pcs                 >> static_phrases.cpp
type \dev\cropsyst\phrases\slprfdlg.pcs                 >> static_phrases.cpp
type \dev\cropsyst\phrases\fmtdlg.pcs                   >> static_phrases.cpp
type \dev\cropsyst\phrases\csbdlg.pcs                   >> static_phrases.cpp
type \dev\cropsyst\phrases\smctldlg.pcs                 >> static_phrases.cpp
type \dev\cropsyst\phrases\arccs.pcs >> static_phrases.cpp

type \dev\cropsyst\phrases\cropsyst.ph  > static_phrases.h
type \dev\cropsyst\phrases\cropfile.ph  >> static_phrases.h
type \dev\cropsyst\phrases\crop.ph      >> static_phrases.h
type \dev\cropsyst\phrases\chem.ph      >> static_phrases.h
type \dev\cropsyst\phrases\et.ph        >> static_phrases.h
type \dev\cropsyst\phrases\erosion.ph   >> static_phrases.h
type \dev\cropsyst\phrases\fmtfile.ph   >> static_phrases.h
type \dev\cropsyst\phrases\mgmtfile.ph  >> static_phrases.h
type \dev\cropsyst\phrases\nitrogen.ph  >> static_phrases.h
type \dev\cropsyst\phrases\residue.ph   >> static_phrases.h
type \dev\cropsyst\phrases\simfile.ph   >> static_phrases.h
type \dev\cropsyst\phrases\project.ph   >> static_phrases.h
type \dev\cropsyst\phrases\scenario.ph   >> static_phrases.h
type \dev\cropsyst\phrases\soilfile.ph  >> static_phrases.h
type \dev\cropsyst\phrases\soil.ph      >> static_phrases.h
type \dev\cropsyst\phrases\rptoptns.ph  >> static_phrases.h
type \dev\cropsyst\phrases\cs_chem.ph   >> static_phrases.h
type \dev\cropsyst\phrases\cs_crops.ph  >> static_phrases.h
type \dev\cropsyst\phrases\cs_grow.ph  >> static_phrases.h
type \dev\cropsyst\phrases\cs_rprt.ph   >> static_phrases.h
type \dev\cropsyst\phrases\cs_till.ph   >> static_phrases.h
type \dev\cropsyst\phrases\cs_event.ph   >> static_phrases.h
type \dev\cropsyst\phrases\csc.ph   >> static_phrases.h
type \dev\cropsyst\phrases\phensync.ph  >> static_phrases.h
type \dev\cropsyst\phrases\validate.ph  >> static_phrases.h
type \dev\cropsyst\phrases\watertab.ph  >> static_phrases.h
type \dev\cropsyst\phrases\cs_rslts.ph  >> static_phrases.h
REM type \dev\cropsyst\phrases\params.ph               >> static_phrases.h
type \dev\corn\datetime\date.ph               >> static_phrases.h
REM date.pc will be hand done in some cases????
REM type \dev\corn\validtyp.ph           >> static_phrases.h  This will be hand done
type \dev\corn\units.ph              >> static_phrases.h
type \dev\common\units.ph     >> static_phrases.h
type \dev\common\measure\units.ph     >> static_phrases.h
type \dev\common\weather\units.ph     >> static_phrases.h
type \dev\common\soil\scs\scs.ph       >> static_phrases.h
type \dev\common\weather\locfile.ph   >> static_phrases.h
type \dev\common\weather\wthrfile.ph  >> static_phrases.h
type \dev\common\weather\weather.ph   >> static_phrases.h
type \dev\common\soil\texttri.ph   >> static_phrases.h
REM The following are for the parameter editor
type \dev\corn\rui\formdlg.ph            >> static_phrases.h
type \dev\corn\rui\filedlg.ph            >> static_phrases.h
type \dev\cropsyst\phrases\tilsldlg.ph                 >> static_phrases.h
type \dev\cropsyst\phrases\mgmtdlg.ph                  >> static_phrases.h
type \dev\cropsyst\phrases\optdlg.ph                   >> static_phrases.h
type \dev\cropsyst\phrases\smrotdlg.ph                 >> static_phrases.h
type \dev\cropsyst\phrases\slprfdlg.ph                 >> static_phrases.h
type \dev\cropsyst\phrases\fmtdlg.ph                   >> static_phrases.h
type \dev\cropsyst\phrases\csbdlg.ph                   >> static_phrases.h
type \dev\cropsyst\phrases\smctldlg.ph                 >> static_phrases.h
type \dev\cropsyst\phrases\arccs.ph >> static_phrases.h

REM copy *.pp ..\pascal

copy \dev\corn\datetime\date.phr \cs_suite\common\phrases\date.phr

