#include "cs_vars_abbrv.h"

#include "csvc.h"


struct CSVC_abbreviations csvc_abbreviations[] =             // name is up to 8 characters
{{CSVC_crop_base_name                                          ,"cropname"}
,{CSVC_crop_base_growing_degree_days_period_accum              ,"Gdegdays"}
,{CSVC_crop_base_seasonal_thermal_time_period_sum              ,"trmltime"}
,{CSVC_crop_biomass_canopy                                     ,"dryBM"}
,{CSVC_crop_biomass_roots_live                                 ,"rootBM"}  // maybe obsolete
,{CSVC_crop_base_fruit_biomass                                 ,"fruitBM"}
,{CSVC_crop_base_fruit_canopy_biomass                          ,"frtcanBM"}
#ifdef OBSOLETE
,{CSVC_crop_base_orchard_solid_canopy_interception             ,"cnpyint"}
,{CSVC_crop_base_orchard_shaded_area_GAI                       ,"shdarea"}
,{CSVC_crop_base_orchard_canopy_porosity                       ,"cnpyprst"}
#endif

,{CSVC_crop_biomass_produced_above_ground_period_sum           ,"abvgndBM"}
,{CSVC_crop_base_root_biomass_current                          ,"rootBM"}
,{CSVC_crop_base_flower_temperature_stress_index_period_avg    ,"Tstrflwr"}
,{CSVC_crop_base_tuber_init_temp_stress_index                  ,"TstrtbrI"}
,{CSVC_crop_base_tuber_fill_temp_stress_index                  ,"TstrtbrF"}

,{CSVC_crop_base_leaf_area_index                               ,"LAI"}
,{CSVC_crop_base_green_area_index                              ,"GAI"}
,{CSVC_crop_base_root_depth                                    ,"rootdpth"}
,{CSVC_crop_base_water_stress_factor                           ,"Wstrss"}
,{CSVC_crop_base_water_stress_factor_period_avg                ,"WstrssA"}
,{CSVC_crop_base_temperature_stress_factor                     ,"Tstrss"}
,{CSVC_crop_base_temperature_stress_factor_period_avg          ,"TstrssA"}
,{CSVC_crop_base_water_stress_index                            ,"WstrssI"}
,{CSVC_crop_base_water_stress_index_period_avg                 ,"WstrssIA"}
,{CSVC_crop_base_temperature_stress_index                      ,"TstrssI"}
,{CSVC_crop_base_temperature_stress_index_period_avg           ,"TstrssIA"}
,{CSVC_crop_base_fract_canopy_cover                            ,"frctcnpy"}
,{CSVC_crop_base_transp_pot_time_step_sum                      ,"TRpotT"}
,{CSVC_crop_base_transp_pot_period_sum                         ,"TRpotP"}
,{CSVC_crop_base_transp_pot_accum_to_date_time                 ,"TRpotC"}
,{CSVC_crop_base_transp_act_time_step_sum                      ,"TRactT"}
,{CSVC_crop_base_transp_act_period_sum                         ,"TRactP"}
,{CSVC_crop_base_transp_act_accum_to_date_time                 ,"TRactC"}
,{CSVC_crop_base_water_intrcpt_time_step_sum                   ,"WintrcpT"}
,{CSVC_crop_base_water_intrcpt_period_sum                      ,"WintrcpP"}
,{CSVC_crop_base_water_intrcpt_accum_to_date_time              ,"WintrcpC"}
,{CSVC_crop_base_growth_stage                                  ,"grwthstg"}
,{CSVC_crop_base_planting_date_YMD                             ,"plant"}
,{CSVC_crop_base_emergence_date_YMD                            ,"emerge"}
,{CSVC_crop_base_flowering_date_YMD                            ,"flower"}
,{CSVC_crop_base_tuber_init_date_YMD                           ,"tbrinit"}
,{CSVC_crop_base_grain_filling_date_YMD                        ,"grainfil"}
,{CSVC_crop_base_peak_LAI_date_YMD                             ,"peakLAI"}
,{CSVC_crop_base_maturity_date_YMD                             ,"maturity"}
,{CSVC_crop_base_harvest_date_YMD                              ,"harvest"}
,{CSVC_crop_base_restart_date_YMD                              ,"restart"}

,{CSVC_crop_base_bud_break_date_YMD                            ,"budbrk"}
,{CSVC_crop_base_initial_fruit_growth_date_YMD                 ,"inifruit"}
,{CSVC_crop_base_rapid_fruit_growth_date_YMD                   ,"rpdfruit"}
,{CSVC_crop_base_inactive_begin_date_YMD                       ,"inactbeg"}
,{CSVC_crop_base_inactive_end_date_YMD                         ,"inactend"}
,{CSVC_crop_base_base_chill_requirement_satisfied_date_YMD     ,"chillsat"}

,{CSVC_crop_base_planting_date_YD                              ,"plant"}
,{CSVC_crop_base_emergence_date_YD                             ,"emerge"}
,{CSVC_crop_base_flowering_date_YD                             ,"flower"}
,{CSVC_crop_base_tuber_init_date_YD                            ,"tbrinit"}
,{CSVC_crop_base_grain_filling_date_YD                         ,"grainfil"}
,{CSVC_crop_base_peak_LAI_date_YD                              ,"peakLAI"}
,{CSVC_crop_base_maturity_date_YD                              ,"maturity"}
,{CSVC_crop_base_harvest_date_YD                               ,"harvest"}
,{CSVC_crop_base_restart_date_YD                               ,"restart"}

,{CSVC_crop_base_bud_break_date_YD                             ,"budbrk"}
,{CSVC_crop_base_initial_fruit_growth_date_YD                  ,"inifruit"}
,{CSVC_crop_base_rapid_fruit_growth_date_YD                    ,"rpdfruit"}
,{CSVC_crop_base_inactive_begin_date_YD                        ,"inactbeg"}
,{CSVC_crop_base_inactive_end_date_YD                          ,"inactend"}
,{CSVC_crop_base_chill_requirement_satisfied_date_YD           ,"chillsat"}

,{CSVC_crop_base_peak_LAI_time_step_max                        ,"LAImax"}
,{CSVC_crop_biomass_yield                                      ,"yield"}
,{CSVC_crop_biomass_useful                                     ,"usedBM"}
,{CSVC_crop_biomass_removed_grazing                            ,"grazedBM"}
,{CSVC_crop_biomass_removed_residue                            ,"residuBM"}
,{CSVC_crop_biomass_disposal                                   ,"dispsdBM"}
,{CSVC_crop_biomass_stubble                                    ,"stbbleBM"}
,{CSVC_crop_biomass_uncut_canopy                               ,"uncutBM"}
,{CSVC_crop_biomass_yield_period_sum                           ,"yieldP"}
,{CSVC_crop_biomass_useful_period_sum                          ,"usedBMP"}
,{CSVC_crop_biomass_removed_grazing_period_sum                 ,"grzdBMP"}
,{CSVC_crop_biomass_removed_residue_period_sum                 ,"rsduBMP"}
,{CSVC_crop_biomass_disposal_period_sum                        ,"dspsBMP"}
,{CSVC_crop_biomass_yield_time_step_sum                        ,"yieldT"}
,{CSVC_crop_biomass_useful_time_step_sum                       ,"usedBMT"}
,{CSVC_crop_biomass_removed_grazing_time_step_sum              ,"grzdBMT"}
,{CSVC_crop_biomass_removed_residue_time_step_sum              ,"rsduBMT"}
,{CSVC_crop_biomass_disposal_time_step_sum                     ,"dspsBMT"}
,{CSVC_crop_base_intercepted_PAR                               ,"intPAR"}
,{CSVC_crop_base_intercepted_PAR_period_sum                    ,"intPARP"}
,{CSVC_crop_base_intercepted_PAR_accum_to_date_time            ,"intPARC"}
,{CSVC_crop_base_VPD_daytime                                   ,"VPDday"}
,{CSVC_crop_base_VPD_daytime_period_avg                        ,"VPDdayA"}

// crop nitrogen
,{CSVC_crop_N_stress_factor                                    ,"Nstrss"}
,{CSVC_crop_N_stress_factor_period_avg                         ,"NstrssA"}
,{CSVC_crop_N_stress_index                                     ,"NstrssI"}
,{CSVC_crop_N_stress_index_period_avg                          ,"NstrssIA"}
,{CSVC_crop_N_uptake_time_step_sum                             ,"NupT"}
,{CSVC_crop_N_uptake_period_sum                                ,"NupP"}
,{CSVC_crop_N_uptake_accum_to_date_time                        ,"NupC"}
,{CSVC_crop_N_mass_canopy_production_accum_to_date_time        ,"NcanA"/*LML 140915 "NmasscanA"*/}
,{CSVC_crop_N_mass_canopy_current                              ,"NcanP"/*LML 140915 NmasscanP"*/}
//110915,{CSVC_crop_N_canopy_assimilation_accum_to_date_time           ,"Nassm"}
,{CSVC_crop_N_conc_canopy                                      ,"Ncnconc"}
,{CSVC_crop_N_conc_roots_live                                  ,"Nrtconc"}
,{CSVC_crop_N_conc_min                                         ,"Nmnconc"}
,{CSVC_crop_N_conc_max                                         ,"Nmxconc"}
,{CSVC_crop_N_conc_critical                                    ,"Ncrconc"}
,{CSVC_crop_N_automatic_uptake_time_step_sum                   ,"NautoT"}
,{CSVC_crop_N_automatic_uptake_period_sum                      ,"NautoP"}
,{CSVC_crop_N_automatic_uptake_accum_to_date_time              ,"NautoC"}
,{CSVC_crop_N_fixation                                         ,"Nfixtn"}
,{CSVC_crop_N_fixation_time_step_sum                           ,"NfixtnT"}
,{CSVC_crop_N_fixation_period_sum                              ,"NfixtnP"}
,{CSVC_crop_N_fixation_accum_to_date_time                      ,"NfixtnC"}

//,{GS_nitrogen_available                                        ,"Navail"}
//,{GS_mineralized_from_residue                                  ,"Nmrlres"}
//,{GS_mineralized_from_org_fert                                 ,"Nmrlmnr"}
//,{GS_mineralized_OM                                            ,"NmrlOM"}
//,{GS_total_mineralization                                      ,"Nmrlttl"}
//,{GS_organic_N_applied                                         ,"Norgapl"}
//,{GS_organic_N_gaseous_loss                                    ,"Norggas"}
//,{GS_inorganic_N_gaseous_loss                                  ,"Nirggas"}
//,{GS_N_fixation                                                ,"Nfix"};


// Residue
,{CSVC_residue_ground_cover                                    ,"RAcvr"}
,{CSVC_residue_water_storage                                   ,"RAwtr"}
,{CSVC_residue_surface_biomass                                 ,"RAsurf"}
,{CSVC_residue_pot_evap_time_step_sum                          ,"RAEpT"}
,{CSVC_residue_pot_evap_accum_to_date_time                     ,"RAEpC"}
,{CSVC_residue_pot_evap_period_sum                             ,"RAEpP"}
,{CSVC_residue_act_evap_time_step_sum                          ,"RAEaT"}
,{CSVC_residue_act_evap_accum_to_date_time                     ,"RAEaC"}
,{CSVC_residue_act_evap_period_sum                             ,"RAEaP"}
,{CSVC_residue_water_intrcpt_time_step_sum                     ,"RAWiT"}
,{CSVC_residue_water_intrcpt_accum_to_date_time                ,"RAWiC"}
,{CSVC_residue_water_intrcpt_period_sum                        ,"RAWiP"}
,{CSVC_residue_mineralized_time_step_sum                       ,"RAminT"}
,{CSVC_residue_mineralized_accum_to_date_time                  ,"RAminC"}
,{CSVC_residue_mineralized_period_sum                          ,"RAminP"}

,{CSVC_residue_incorporated                                    ,"RAinc"}
,{CSVC_residue_incorporated_1                                  ,"RAinc01"}
,{CSVC_residue_incorporated_2                                  ,"RAinc02"}
,{CSVC_residue_incorporated_3                                  ,"RAinc03"}
,{CSVC_residue_incorporated_4                                  ,"RAinc04"}
,{CSVC_residue_incorporated_5                                  ,"RAinc05"}
,{CSVC_residue_incorporated_6                                  ,"RAinc06"}
,{CSVC_residue_incorporated_7                                  ,"RAinc07"}
,{CSVC_residue_incorporated_8                                  ,"RAinc08"}
,{CSVC_residue_incorporated_9                                  ,"RAinc09"}
,{CSVC_residue_incorporated_10                                 ,"RAinc10"}
,{CSVC_residue_incorporated_11                                 ,"RAinc11"}
,{CSVC_residue_incorporated_12                                 ,"RAinc12"}
,{CSVC_residue_incorporated_13                                 ,"RAinc13"}
,{CSVC_residue_incorporated_14                                 ,"RAinc14"}
,{CSVC_residue_incorporated_15                                 ,"RAinc15"}
,{CSVC_residue_incorporated_16                                 ,"RAinc16"}
,{CSVC_residue_incorporated_17                                 ,"RAinc17"}
,{CSVC_residue_incorporated_18                                 ,"RAinc18"}
,{CSVC_residue_incorporated_19                                 ,"RAinc19"}
,{CSVC_residue_incorporated_20                                 ,"RAinc20"}
,{CSVC_residue_incorporated_21                                 ,"RAinc21"}
,{CSVC_residue_incorporated_22                                 ,"RAinc22"}
,{CSVC_residue_incorporated_23                                 ,"RAinc23"}
,{CSVC_residue_incorporated_24                                 ,"RAinc24"}
,{CSVC_residue_incorporated_25                                 ,"RAinc25"}
,{CSVC_residue_incorporated_26                                 ,"RAinc26"}
,{CSVC_residue_incorporated_27                                 ,"RAinc27"}
,{CSVC_residue_incorporated_28                                 ,"RAinc28"}
,{CSVC_residue_incorporated_29                                 ,"RAinc29"}
,{CSVC_residue_incorporated_30                                 ,"RAinc30"}
,{CSVC_residue_incorporated_31                                 ,"RAinc31"}

// Plant residue
,{CSVC_residue_plant_surface                                   ,"RPsurf"}

,{CSVC_residue_plant_incorporated                              ,"RPinc "}
,{CSVC_residue_plant_incorporated_1                            ,"RPinc01"}
,{CSVC_residue_plant_incorporated_2                            ,"RPinc02"}
,{CSVC_residue_plant_incorporated_3                            ,"RPinc03"}
,{CSVC_residue_plant_incorporated_4                            ,"RPinc04"}
,{CSVC_residue_plant_incorporated_5                            ,"RPinc05"}
,{CSVC_residue_plant_incorporated_6                            ,"RPinc06"}
,{CSVC_residue_plant_incorporated_7                            ,"RPinc07"}
,{CSVC_residue_plant_incorporated_8                            ,"RPinc08"}
,{CSVC_residue_plant_incorporated_9                            ,"RPinc09"}
,{CSVC_residue_plant_incorporated_10                           ,"RPinc10"}
,{CSVC_residue_plant_incorporated_11                           ,"RPinc11"}
,{CSVC_residue_plant_incorporated_12                           ,"RPinc12"}
,{CSVC_residue_plant_incorporated_13                           ,"RPinc13"}
,{CSVC_residue_plant_incorporated_14                           ,"RPinc14"}
,{CSVC_residue_plant_incorporated_15                           ,"RPinc15"}
,{CSVC_residue_plant_incorporated_16                           ,"RPinc16"}
,{CSVC_residue_plant_incorporated_17                           ,"RPinc17"}
,{CSVC_residue_plant_incorporated_18                           ,"RPinc18"}
,{CSVC_residue_plant_incorporated_19                           ,"RPinc19"}
,{CSVC_residue_plant_incorporated_20                           ,"RPinc20"}
,{CSVC_residue_plant_incorporated_21                           ,"RPinc21"}
,{CSVC_residue_plant_incorporated_22                           ,"RPinc22"}
,{CSVC_residue_plant_incorporated_23                           ,"RPinc23"}
,{CSVC_residue_plant_incorporated_24                           ,"RPinc24"}
,{CSVC_residue_plant_incorporated_25                           ,"RPinc25"}
,{CSVC_residue_plant_incorporated_26                           ,"RPinc26"}
,{CSVC_residue_plant_incorporated_27                           ,"RPinc27"}
,{CSVC_residue_plant_incorporated_28                           ,"RPinc28"}
,{CSVC_residue_plant_incorporated_29                           ,"RPinc29"}
,{CSVC_residue_plant_incorporated_30                           ,"RPinc30"}
,{CSVC_residue_plant_incorporated_31                           ,"RPinc31"}

// Manure
,{CSVC_residue_manure_mineralized_time_step_sum                ,"RMmnrlT"}
,{CSVC_residue_manure_mineralized_accum_to_date_time           ,"RMmnrlC"}
,{CSVC_residue_manure_mineralized_period_sum                   ,"RMmnrlP"}
,{CSVC_residue_manure_surface                                  ,"RMsurf"}

,{CSVC_residue_manure_incorporated                             ,"RMinc "}
,{CSVC_residue_manure_incorporated_1                           ,"RMinc01"}
,{CSVC_residue_manure_incorporated_2                           ,"RMinc02"}
,{CSVC_residue_manure_incorporated_3                           ,"RMinc03"}
,{CSVC_residue_manure_incorporated_4                           ,"RMinc04"}
,{CSVC_residue_manure_incorporated_5                           ,"RMinc05"}
,{CSVC_residue_manure_incorporated_6                           ,"RMinc06"}
,{CSVC_residue_manure_incorporated_7                           ,"RMinc07"}
,{CSVC_residue_manure_incorporated_8                           ,"RMinc08"}
,{CSVC_residue_manure_incorporated_9                           ,"RMinc09"}
,{CSVC_residue_manure_incorporated_10                          ,"RMinc10"}
,{CSVC_residue_manure_incorporated_11                          ,"RMinc11"}
,{CSVC_residue_manure_incorporated_12                          ,"RMinc12"}
,{CSVC_residue_manure_incorporated_13                          ,"RMinc13"}
,{CSVC_residue_manure_incorporated_14                          ,"RMinc14"}
,{CSVC_residue_manure_incorporated_15                          ,"RMinc15"}
,{CSVC_residue_manure_incorporated_16                          ,"RMinc16"}
,{CSVC_residue_manure_incorporated_17                          ,"RMinc17"}
,{CSVC_residue_manure_incorporated_18                          ,"RMinc18"}
,{CSVC_residue_manure_incorporated_19                          ,"RMinc19"}
,{CSVC_residue_manure_incorporated_20                          ,"RMinc20"}
,{CSVC_residue_manure_incorporated_21                          ,"RMinc21"}
,{CSVC_residue_manure_incorporated_22                          ,"RMinc22"}
,{CSVC_residue_manure_incorporated_23                          ,"RMinc23"}
,{CSVC_residue_manure_incorporated_24                          ,"RMinc24"}
,{CSVC_residue_manure_incorporated_25                          ,"RMinc25"}
,{CSVC_residue_manure_incorporated_26                          ,"RMinc26"}
,{CSVC_residue_manure_incorporated_27                          ,"RMinc27"}
,{CSVC_residue_manure_incorporated_28                          ,"RMinc28"}
,{CSVC_residue_manure_incorporated_29                          ,"RMinc29"}
,{CSVC_residue_manure_incorporated_30                          ,"RMinc30"}
,{CSVC_residue_manure_incorporated_31                          ,"RMinc31"}

// Weather
,{CSVC_weather_precipitation_time_step_sum                     ,"precipT"}
,{CSVC_weather_precipitation_accum_to_date_time                ,"precipC"}
,{CSVC_weather_precipitation_period_sum                        ,"precipP"}
,{CSVC_weather_snow_storage                                    ,"snowstrg"}
,{CSVC_weather_temperature_time_step_min                       ,"Tairmax"}
,{CSVC_weather_temperature_time_step_max                       ,"Tairmin"}
,{CSVC_weather_solar_radiation                                 ,"solarrad"}

// Weather date
,{CSVC_weather_date_year_day                                   ,"yearDOY"}
,{CSVC_weather_date_year                                       ,"year"}
,{CSVC_weather_date_DOY                                        ,"DOY"}
,{CSVC_weather_date_month                                      ,"month"}
,{CSVC_weather_date_DOM                                        ,"dom"}

// ET
,{CSVC_weather_ET_pot_time_step_sum                            ,"ETpotT"}
,{CSVC_weather_ET_act_time_step_sum                            ,"ETactT"}
,{CSVC_weather_ET_ref_time_step_sum                            ,"ETrefT"}        //160822
,{CSVC_weather_ET_pot_accum_to_date_time                       ,"ETpotC"}
,{CSVC_weather_ET_act_accum_to_date_time                       ,"ETactC"}
,{CSVC_weather_ET_ref_accum_to_date_time                       ,"ETrefC"}
,{CSVC_weather_ET_pot_period_sum                               ,"ETpotP"}
,{CSVC_weather_ET_act_period_sum                               ,"ETactP"}
,{CSVC_weather_ET_ref_period_sum                               ,"ETrefP"}

// Soil base
,{CSVC_soil_base_evap_pot_time_step_sum                        ,"soilEpT"}
,{CSVC_soil_base_evap_pot_accum_to_date_time                   ,"soilEpC"}
,{CSVC_soil_base_evap_pot_period_sum                           ,"soilEpP"}
,{CSVC_soil_base_evap_act_time_step_sum                        ,"soilEaT"}
,{CSVC_soil_base_evap_act_accum_to_date_time                   ,"soilEaC"}
,{CSVC_soil_base_evap_act_period_sum                           ,"soilEaP"}
,{CSVC_soil_base_water_entering_time_step_sum                  ,"WEsoilT"}
,{CSVC_soil_base_water_entering_accum_to_date_time             ,"WEsoilC"}
,{CSVC_soil_base_water_entering_period_sum                     ,"WEsoilP"}
,{CSVC_soil_base_water_drainage_time_step_sum                  ,"drianT"}
,{CSVC_soil_base_water_drainage_accum_to_date_time             ,"drainC"}
,{CSVC_soil_base_water_drainage_period_sum                     ,"drainP"}
//131007 ,{CSVC_soil_base_water_depletion_accum_to_date_time            ,"deplettn"}
,{CSVC_soil_base_water_depletion_balance_accum_to_date_time    ,"deplttnA"}      //131007
,{CSVC_soil_base_water_depletion_seasonal_period_sum           ,"deplttnP"}      //131007
,{CSVC_soil_base_water_balance_accum_to_date_time              ,"WbalC"}
,{CSVC_soil_base_water_balance_time_step_sum                   ,"WbalT"}

// soil erosion
,{CSVC_soil_erosion_clod_rate                                  ,"ersnclod"}
,{CSVC_soil_erosion_loss_time_step_sum                         ,"ersnlssT"}
,{CSVC_soil_erosion_loss_period_sum                            ,"ersnlssP"}
,{CSVC_soil_erosion_index_period_sum                           ,"ersnndx"}
,{CSVC_soil_erosion_RUSLE_C_factor_time_step_sum               ,"RUSLEC"}

// soil runoff
,{CSVC_soil_runoff_surface_water_runoff_time_step_sum          ,"WroffT"}
,{CSVC_soil_runoff_surface_water_runoff_accum_to_date_time     ,"WroffC"}
,{CSVC_soil_runoff_surface_water_runoff_period_sum             ,"WroffP"}
,{CSVC_soil_runoff_surface_water_runon_time_step_sum           ,"WronT"}

// carbon soil
//060418,{CSVC_soil_C_all_profile_time_step_sum                       ,"CprofT"}
//060418,{CSVC_soil_C_all_30cm_time_step_sum                          ,"C30cmT"}

,{CSVC_soil_C_all_profile                                      ,"Callprof"}
,{CSVC_soil_C_all_5cm                                          ,"Call5cm"}
,{CSVC_soil_C_all_30cm                                         ,"Call30cm"}
,{CSVC_soil_C_all_60cm                                         ,"Call60cm"}
,{CSVC_soil_C_all_90cm                                         ,"Call90cm"}

,{CSVC_soil_C_SOM_profile                                      ,"CSOMprof"}
,{CSVC_soil_C_SOM_5cm                                          ,"CSOM5cm"}
,{CSVC_soil_C_SOM_30cm                                         ,"CSOM30cm"}
,{CSVC_soil_C_SOM_60cm                                         ,"CSOM60cm"}
,{CSVC_soil_C_SOM_90cm                                         ,"CSOM90cm"}
,{CSVC_soil_C_microbial_profile                                ,"Cmblprof"}
,{CSVC_soil_C_microbial_5cm                                    ,"Cmbl5cm"}
,{CSVC_soil_C_microbial_30cm                                   ,"Cmbl30cm"}
,{CSVC_soil_C_microbial_60cm                                   ,"Cmbl60cm"}
,{CSVC_soil_C_microbial_90cm                                   ,"Cmbl90cm"}
,{CSVC_soil_C_labile_profile                                   ,"Clabprof"}
,{CSVC_soil_C_labile_5cm                                       ,"Clab5cm"}
,{CSVC_soil_C_labile_30cm                                      ,"Clab30cm"}
,{CSVC_soil_C_labile_60cm                                      ,"Clab60cm"}
,{CSVC_soil_C_labile_90cm                                      ,"Clab90cm"}
,{CSVC_soil_C_metastable_profile                               ,"Cmtsprof"}
,{CSVC_soil_C_metastable_5cm                                   ,"Cmts5cm"}
,{CSVC_soil_C_metastable_30cm                                  ,"Cmts30cm"}
,{CSVC_soil_C_metastable_60cm                                  ,"Cmts60cm"}
,{CSVC_soil_C_metastable_90cm                                  ,"Cmts90cm"}
,{CSVC_soil_C_passive_profile                                  ,"Cpsvprof"}
,{CSVC_soil_C_passive_5cm                                      ,"Cpsv5cm"}
,{CSVC_soil_C_passive_30cm                                     ,"Cpsv30cm"}
,{CSVC_soil_C_passive_60cm                                     ,"Cpsv60cm"}
,{CSVC_soil_C_passive_90cm                                     ,"Cpsv90cm"}

// soil nitrogen
,{CSVC_soil_N_leached_time_step_sum                            ,"NleachT"}
,{CSVC_soil_N_leached_accum_to_date_time                       ,"NleachC"}
,{CSVC_soil_N_leached_period_avg                               ,"NleachA"}
,{CSVC_soil_N_leached_period_sum                               ,"NleachP"}
,{CSVC_soil_N_available_period_sum                             ,"NavailP"}
,{CSVC_soil_N_NH3_volatilization_time_step_sum                 ,"NH3NvolT"}
,{CSVC_soil_N_NH3_volatilization_accum_to_date_time            ,"NH3NvolC"}
,{CSVC_soil_N_NH3_volatilization_period_sum                    ,"NH3NvolP"}
,{CSVC_soil_N_input_time_step_sum                              ,"NinT"}
,{CSVC_soil_N_input_accum_to_date_time                         ,"NinC"}
,{CSVC_soil_N_input_period_sum                                 ,"NinP"}
,{CSVC_soil_N_output_time_step_sum                             ,"NoutT"}
,{CSVC_soil_N_output_accum_to_date_time                        ,"NoutC"}
,{CSVC_soil_N_output_period_sum                                ,"NoutP"}
,{CSVC_soil_N_immobilization_time_step_sum                     ,"NimblT"}
,{CSVC_soil_N_immobilization_accum_to_date_time                ,"NimblC"}
,{CSVC_soil_N_immobilization_period_sum                        ,"NimblP"}

,{CSVC_soil_N_immobilization_profile_time_step_sum             ,"NimblprT"}
,{CSVC_soil_N_immobilization_5cm_time_step_sum                 ,"Nimbl05T"}
,{CSVC_soil_N_immobilization_30cm_time_step_sum                ,"Nimbl30T"}
,{CSVC_soil_N_immobilization_60cm_time_step_sum                ,"Nimbl60T"}
,{CSVC_soil_N_immobilization_90cm_time_step_sum                ,"Nimbl90T"}


// Soil pond
,{CSVC_soil_pond_water_depth                                   ,"ponddpth"}

// Management
,{CSVC_mgmt_irrig_applied_time_step_sum                        ,"irrigT"}
,{CSVC_mgmt_irrig_applied_accum_to_date_time                   ,"irrigC"}
,{CSVC_mgmt_irrig_applied_period_sum                           ,"irrigP"}
,{CSVC_mgmt_biomass_grazed_time_step_sum                       ,"BMgrzdT"}
,{CSVC_mgmt_biomass_grazed_accum_to_date_time                  ,"BMgrzdC"}

// Nitrogen management
,{CSVC_mgmt_N_applied_time_step_sum                            ,"NinorgT"}
,{CSVC_mgmt_N_applied_accum_to_date_time                       ,"NinorgC"}
,{CSVC_mgmt_N_applied_period_sum                               ,"NinorgP"}
,{CSVC_mgmt_N_organic_applied_time_step_sum                    ,"NorgT"}
,{CSVC_mgmt_N_organic_applied_accum_to_date_time               ,"NorgC"}
,{CSVC_mgmt_N_organic_applied_period_sum                       ,"NorgP"}
,{CSVC_mgmt_N_organic_gaseous_loss_time_step_sum               ,"NorggasT"}
,{CSVC_mgmt_N_organic_gaseous_loss_accum_to_date_time          ,"NorggasC"}
,{CSVC_mgmt_N_organic_gaseous_loss_period_sum                  ,"NorggasP"}
,{CSVC_mgmt_N_inorganic_gaseous_loss_time_step_sum             ,"NinrggsT"}
,{CSVC_mgmt_N_inorganic_gaseous_loss_accum_to_date_time        ,"NinrggsC"}
,{CSVC_mgmt_N_inorganic_gaseous_loss_period_sum                ,"NinorgsP"}

// Not that these mineralization declarations probably should be moved (to soil N  or residue N?)
,{CSVC_misc_N_total_mineralization_time_step_sum               ,"NtotminT"}
,{CSVC_misc_N_total_mineralization_period_sum                  ,"NtotminP"}

,{CSVC_soil_base_water_content                                 ,"WC"}
,{CSVC_soil_base_water_content_1                               ,"WC01"}
,{CSVC_soil_base_water_content_2                               ,"WC02"}
,{CSVC_soil_base_water_content_3                               ,"WC03"}
,{CSVC_soil_base_water_content_4                               ,"WC04"}
,{CSVC_soil_base_water_content_5                               ,"WC05"}
,{CSVC_soil_base_water_content_6                               ,"WC06"}
,{CSVC_soil_base_water_content_7                               ,"WC07"}
,{CSVC_soil_base_water_content_8                               ,"WC08"}
,{CSVC_soil_base_water_content_9                               ,"WC09"}
,{CSVC_soil_base_water_content_10                              ,"WC10"}
,{CSVC_soil_base_water_content_11                              ,"WC11"}
,{CSVC_soil_base_water_content_12                              ,"WC12"}
,{CSVC_soil_base_water_content_13                              ,"WC13"}
,{CSVC_soil_base_water_content_14                              ,"WC14"}
,{CSVC_soil_base_water_content_15                              ,"WC15"}
,{CSVC_soil_base_water_content_16                              ,"WC16"}
,{CSVC_soil_base_water_content_17                              ,"WC17"}
,{CSVC_soil_base_water_content_18                              ,"WC18"}
,{CSVC_soil_base_water_content_19                              ,"WC19"}
,{CSVC_soil_base_water_content_20                              ,"WC20"}
,{CSVC_soil_base_water_content_21                              ,"WC21"}
,{CSVC_soil_base_water_content_22                              ,"WC22"}
,{CSVC_soil_base_water_content_23                              ,"WC23"}
,{CSVC_soil_base_water_content_24                              ,"WC24"}
,{CSVC_soil_base_water_content_25                              ,"WC25"}
,{CSVC_soil_base_water_content_26                              ,"WC26"}
,{CSVC_soil_base_water_content_27                              ,"WC27"}
,{CSVC_soil_base_water_content_28                              ,"WC28"}
,{CSVC_soil_base_water_content_29                              ,"WC29"}
,{CSVC_soil_base_water_content_30                              ,"WC30"}
,{CSVC_soil_base_water_content_31                              ,"WC31"}

,{CSVC_soil_base_plant_avail_water                             ,"PAW"}
,{CSVC_soil_base_plant_avail_water_1                           ,"PAW01"}
,{CSVC_soil_base_plant_avail_water_2                           ,"PAW02"}
,{CSVC_soil_base_plant_avail_water_3                           ,"PAW03"}
,{CSVC_soil_base_plant_avail_water_4                           ,"PAW04"}
,{CSVC_soil_base_plant_avail_water_5                           ,"PAW05"}
,{CSVC_soil_base_plant_avail_water_6                           ,"PAW06"}
,{CSVC_soil_base_plant_avail_water_7                           ,"PAW07"}
,{CSVC_soil_base_plant_avail_water_8                           ,"PAW08"}
,{CSVC_soil_base_plant_avail_water_9                           ,"PAW09"}
,{CSVC_soil_base_plant_avail_water_10                          ,"PAW10"}
,{CSVC_soil_base_plant_avail_water_11                          ,"PAW11"}
,{CSVC_soil_base_plant_avail_water_12                          ,"PAW12"}
,{CSVC_soil_base_plant_avail_water_13                          ,"PAW13"}
,{CSVC_soil_base_plant_avail_water_14                          ,"PAW14"}
,{CSVC_soil_base_plant_avail_water_15                          ,"PAW15"}
,{CSVC_soil_base_plant_avail_water_16                          ,"PAW16"}
,{CSVC_soil_base_plant_avail_water_17                          ,"PAW17"}
,{CSVC_soil_base_plant_avail_water_18                          ,"PAW18"}
,{CSVC_soil_base_plant_avail_water_19                          ,"PAW19"}
,{CSVC_soil_base_plant_avail_water_20                          ,"PAW20"}
,{CSVC_soil_base_plant_avail_water_21                          ,"PAW21"}
,{CSVC_soil_base_plant_avail_water_22                          ,"PAW22"}
,{CSVC_soil_base_plant_avail_water_23                          ,"PAW23"}
,{CSVC_soil_base_plant_avail_water_24                          ,"PAW24"}
,{CSVC_soil_base_plant_avail_water_25                          ,"PAW25"}
,{CSVC_soil_base_plant_avail_water_26                          ,"PAW26"}
,{CSVC_soil_base_plant_avail_water_27                          ,"PAW27"}
,{CSVC_soil_base_plant_avail_water_28                          ,"PAW28"}
,{CSVC_soil_base_plant_avail_water_29                          ,"PAW29"}
,{CSVC_soil_base_plant_avail_water_30                          ,"PAW30"}
,{CSVC_soil_base_plant_avail_water_31                          ,"PAW31"}

,{CSVC_soil_base_water_potential                               ,"WP"}
,{CSVC_soil_base_water_potential_1                             ,"WP01"}
,{CSVC_soil_base_water_potential_2                             ,"WP02"}
,{CSVC_soil_base_water_potential_3                             ,"WP03"}
,{CSVC_soil_base_water_potential_4                             ,"WP04"}
,{CSVC_soil_base_water_potential_5                             ,"WP05"}
,{CSVC_soil_base_water_potential_6                             ,"WP06"}
,{CSVC_soil_base_water_potential_7                             ,"WP07"}
,{CSVC_soil_base_water_potential_8                             ,"WP08"}
,{CSVC_soil_base_water_potential_9                             ,"WP09"}
,{CSVC_soil_base_water_potential_10                            ,"WP10"}
,{CSVC_soil_base_water_potential_11                            ,"WP11"}
,{CSVC_soil_base_water_potential_12                            ,"WP12"}
,{CSVC_soil_base_water_potential_13                            ,"WP13"}
,{CSVC_soil_base_water_potential_14                            ,"WP14"}
,{CSVC_soil_base_water_potential_15                            ,"WP15"}
,{CSVC_soil_base_water_potential_16                            ,"WP16"}
,{CSVC_soil_base_water_potential_17                            ,"WP17"}
,{CSVC_soil_base_water_potential_18                            ,"WP18"}
,{CSVC_soil_base_water_potential_19                            ,"WP19"}
,{CSVC_soil_base_water_potential_20                            ,"WP20"}
,{CSVC_soil_base_water_potential_21                            ,"WP21"}
,{CSVC_soil_base_water_potential_22                            ,"WP22"}
,{CSVC_soil_base_water_potential_23                            ,"WP23"}
,{CSVC_soil_base_water_potential_24                            ,"WP24"}
,{CSVC_soil_base_water_potential_25                            ,"WP25"}
,{CSVC_soil_base_water_potential_26                            ,"WP26"}
,{CSVC_soil_base_water_potential_27                            ,"WP27"}
,{CSVC_soil_base_water_potential_28                            ,"WP28"}
,{CSVC_soil_base_water_potential_29                            ,"WP29"}
,{CSVC_soil_base_water_potential_30                            ,"WP30"}
,{CSVC_soil_base_water_potential_31                            ,"WP31"}
/*NYN
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum           ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_1         ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_2         ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_3         ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_4         ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_5         ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_6         ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_7         ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_8         ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_9         ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_10        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_11        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_12        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_13        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_14        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_15        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_16        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_17        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_18        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_19        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_20        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_21        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_22        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_23        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_24        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_25        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_26        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_27        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_28        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_29        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_30        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_in_flow_depth_time_step_sum_31        ,"XXXXXXXX"}

,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum          ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_1        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_2        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_3        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_4        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_5        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_6        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_7        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_8        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_9        ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_10       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_11       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_12       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_13       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_14       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_15       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_16       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_17       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_18       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_19       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_20       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_21       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_22       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_23       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_24       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_25       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_26       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_27       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_28       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_29       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_30       ,"XXXXXXXX"}
,{CSVC_soil_base_lateral_out_flow_depth_time_step_sum_31       ,"XXXXXXXX"}
*/
,{CSVC_soil_base_temperature_time_step_avg                     ,"TsoilA"}
,{CSVC_soil_base_temperature_time_step_avg_1                   ,"TsoilA01"}
,{CSVC_soil_base_temperature_time_step_avg_2                   ,"TsoilA02"}
,{CSVC_soil_base_temperature_time_step_avg_3                   ,"TsoilA03"}
,{CSVC_soil_base_temperature_time_step_avg_4                   ,"TsoilA04"}
,{CSVC_soil_base_temperature_time_step_avg_5                   ,"TsoilA05"}
,{CSVC_soil_base_temperature_time_step_avg_6                   ,"TsoilA06"}
,{CSVC_soil_base_temperature_time_step_avg_7                   ,"TsoilA07"}
,{CSVC_soil_base_temperature_time_step_avg_8                   ,"TsoilA08"}
,{CSVC_soil_base_temperature_time_step_avg_9                   ,"TsoilA09"}
,{CSVC_soil_base_temperature_time_step_avg_10                  ,"TsoilA10"}
,{CSVC_soil_base_temperature_time_step_avg_11                  ,"Tsoil111"}
,{CSVC_soil_base_temperature_time_step_avg_12                  ,"TsoilA12"}
,{CSVC_soil_base_temperature_time_step_avg_13                  ,"TsoilA13"}
,{CSVC_soil_base_temperature_time_step_avg_14                  ,"TsoilA14"}
,{CSVC_soil_base_temperature_time_step_avg_15                  ,"TsoilA15"}
,{CSVC_soil_base_temperature_time_step_avg_16                  ,"TsoilA16"}
,{CSVC_soil_base_temperature_time_step_avg_17                  ,"TsoilA17"}
,{CSVC_soil_base_temperature_time_step_avg_18                  ,"TsoilA18"}
,{CSVC_soil_base_temperature_time_step_avg_19                  ,"TsoilA19"}
,{CSVC_soil_base_temperature_time_step_avg_20                  ,"TsoilA20"}
,{CSVC_soil_base_temperature_time_step_avg_21                  ,"TsoilA21"}
,{CSVC_soil_base_temperature_time_step_avg_22                  ,"TsoilA22"}
,{CSVC_soil_base_temperature_time_step_avg_23                  ,"TsoilA23"}
,{CSVC_soil_base_temperature_time_step_avg_24                  ,"TsoilA24"}
,{CSVC_soil_base_temperature_time_step_avg_25                  ,"TsoilA25"}
,{CSVC_soil_base_temperature_time_step_avg_26                  ,"TsoilA26"}
,{CSVC_soil_base_temperature_time_step_avg_27                  ,"TsoilA27"}
,{CSVC_soil_base_temperature_time_step_avg_28                  ,"TsoilA28"}
,{CSVC_soil_base_temperature_time_step_avg_29                  ,"TsoilA29"}
,{CSVC_soil_base_temperature_time_step_avg_30                  ,"TsoilA30"}
,{CSVC_soil_base_temperature_time_step_avg_31                  ,"TsoilA31"}
/*NYN
,{CSVC_soil_N_NO3_amount                                       ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_1                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_2                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_3                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_4                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_5                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_6                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_7                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_8                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_9                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_10                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_11                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_12                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_13                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_14                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_15                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_16                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_17                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_18                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_19                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_20                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_21                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_22                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_23                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_24                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_25                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_26                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_27                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_28                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_29                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_30                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NO3_amount_31                                    ,"XXXXXXXX"}

,{CSVC_soil_N_NH4_amount                                       ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_1                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_2                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_3                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_4                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_5                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_6                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_7                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_8                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_9                                     ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_10                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_11                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_12                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_13                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_14                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_15                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_16                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_17                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_18                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_19                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_20                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_21                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_22                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_23                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_24                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_25                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_26                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_27                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_28                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_29                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_30                                    ,"XXXXXXXX"}
,{CSVC_soil_N_NH4_amount_31                                    ,"XXXXXXXX"}

,{CSVC_soil_N_N_amount                                         ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_1                                       ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_2                                       ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_3                                       ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_4                                       ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_5                                       ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_6                                       ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_7                                       ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_8                                       ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_9                                       ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_10                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_11                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_12                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_13                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_14                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_15                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_16                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_17                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_18                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_19                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_20                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_21                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_22                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_23                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_24                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_25                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_26                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_27                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_28                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_29                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_30                                      ,"XXXXXXXX"}
,{CSVC_soil_N_N_amount_31                                      ,"XXXXXXXX"}

,{CSVC_soil_N_mineralization_time_step_sum                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_1                   ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_2                   ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_3                   ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_4                   ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_5                   ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_6                   ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_7                   ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_8                   ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_9                   ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_10                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_11                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_12                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_13                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_14                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_15                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_16                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_17                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_18                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_19                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_20                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_21                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_22                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_23                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_24                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_25                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_26                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_27                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_28                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_29                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_30                  ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_time_step_sum_31                  ,"XXXXXXXX"}
*/
,{CSVC_soil_N_mineralization_period_sum                        ,"NmnrlP"}
/*
,{CSVC_soil_N_mineralization_period_sum_1                      ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_2                      ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_3                      ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_4                      ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_5                      ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_6                      ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_7                      ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_8                      ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_9                      ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_10                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_11                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_12                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_13                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_14                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_15                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_16                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_17                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_18                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_19                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_20                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_21                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_22                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_23                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_24                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_25                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_26                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_27                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_28                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_29                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_30                     ,"XXXXXXXX"}
,{CSVC_soil_N_mineralization_period_sum_31                     ,"XXXXXXXX"}

,{CSVC_soil_N_nitrification_time_step_sum                      ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_1                    ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_2                    ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_3                    ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_4                    ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_5                    ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_6                    ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_7                    ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_8                    ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_9                    ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_10                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_11                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_12                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_13                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_14                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_15                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_16                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_17                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_18                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_19                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_20                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_21                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_22                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_23                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_24                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_25                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_26                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_27                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_28                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_29                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_30                   ,"XXXXXXXX"}
,{CSVC_soil_N_nitrification_time_step_sum_31                   ,"XXXXXXXX"}

,{CSVC_soil_N_denitrification_time_step_sum                    ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_1                  ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_2                  ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_3                  ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_4                  ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_5                  ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_6                  ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_7                  ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_8                  ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_9                  ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_10                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_11                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_12                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_13                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_14                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_15                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_16                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_17                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_18                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_19                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_20                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_21                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_22                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_23                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_24                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_25                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_26                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_27                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_28                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_29                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_30                 ,"XXXXXXXX"}
,{CSVC_soil_N_denitrification_time_step_sum_31                 ,"XXXXXXXX"}

,{CSVC_crop_base_root_fraction                                 ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_1                               ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_2                               ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_3                               ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_4                               ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_5                               ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_6                               ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_7                               ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_8                               ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_9                               ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_10                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_11                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_12                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_13                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_14                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_15                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_16                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_17                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_18                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_19                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_20                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_21                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_22                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_23                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_24                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_25                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_26                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_27                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_28                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_29                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_30                              ,"XXXXXXXX"}
,{CSVC_crop_base_root_fraction_31                              ,"XXXXXXXX"}

,{CSVC_soil_base_salinity                                      ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_1                                    ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_2                                    ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_3                                    ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_4                                    ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_5                                    ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_6                                    ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_7                                    ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_8                                    ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_9                                    ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_10                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_11                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_12                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_13                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_14                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_15                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_16                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_17                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_18                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_19                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_20                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_21                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_22                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_23                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_24                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_25                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_26                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_27                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_28                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_29                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_30                                   ,"XXXXXXXX"}
,{CSVC_soil_base_salinity_31                                   ,"XXXXXXXX"}
*/
,{CSVC_organic_matter_mineralized_time_step_sum                ,"OMmnrlT"}
,{CSVC_organic_matter_mineralized_accum_to_date_time           ,"OMmnrlC"}
,{CSVC_organic_matter_mineralized_period_sum                   ,"OMmnrlP"}

,{CSVC_organic_matter_N_mineralization_profile_time_step_sum   ,"OMmrlprT"}
,{CSVC_organic_matter_N_mineralization_5cm_time_step_sum       ,"OMmrl05T"}
,{CSVC_organic_matter_N_mineralization_10cm_time_step_sum      ,"OMmrl10T"}
,{CSVC_organic_matter_N_mineralization_15cm_time_step_sum      ,"OMmrl15T"}
,{CSVC_organic_matter_N_mineralization_30cm_time_step_sum      ,"OMmrl30T"}
,{CSVC_organic_matter_N_mineralization_60cm_time_step_sum      ,"OMmrl60T"}
,{CSVC_organic_matter_N_mineralization_90cm_time_step_sum      ,"OMmrl90T"}

,{CSVC_soil_N_N2O_loss_denitrification_time_step_sum   ,"N2Odntr"}
,{CSVC_soil_N_N2O_loss_nitrification_time_step_sum     ,"N2Ontr"}


/*NYN
,{CSVC_organic_matter_percent_time_step_sum                    ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_1                  ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_2                  ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_3                  ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_4                  ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_5                  ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_6                  ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_7                  ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_8                  ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_9                  ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_10                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_11                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_12                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_13                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_14                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_15                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_16                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_17                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_18                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_19                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_20                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_21                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_22                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_23                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_24                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_25                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_26                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_27                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_28                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_29                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_30                 ,"XXXXXXXX"}
,{CSVC_organic_matter_percent_time_step_sum_31                 ,"XXXXXXXX"}
*/
,{CSVC_organic_matter_CO2_C_loss_OM_time_step_sum ,"OM_C_los"/*LML 140915 "OM_C_loss"*/}
,{0,""}
};
