#include "C:\dev\corn\measure\units.h"
#include <corn/std/std_iomanip.h>
//060406 #include <iomanip.h>

void main()
 {
ofstream CS("units_codes.cs");
ofstream Cpp("units_codes.h");
ofstream VB("units_code.bas");
CS  << "#pragma once" << endl;
CS  << "namespace UED_simple" << endl;
CS  << "{" << endl;
Cpp  << "#ifndef UED_SIMPLE_UNITS_CODE" << endl;
Cpp  << "#define UED_SIMPLE_UNITS_CODE" << endl;
Cpp  << "namespace UED_simple" << endl;
Cpp  << "{" << endl;
VB  << "Option Explicit" << endl; 
VB  << "Attribute VB_name = \"UED_simple\"" << endl; 
CS  << "   public const uint UC_unitless = " << hex <<"0x"<< UC_unitless << " ;" << endl;
Cpp << "#define UC_unitless " << hex <<"0x"<< UC_unitless <<  endl;
VB  << "public const UC_unitless as long = " << UC_unitless << " ;" << endl;
CS  << "   public const uint UC_code = " << hex <<"0x"<< UC_code << " ;" << endl;
Cpp << "#define UC_code " << hex <<"0x"<< UC_code <<  endl;
VB  << "public const UC_code as long = " << UC_code << " ;" << endl;
CS  << "   public const uint UC_unit = " << hex <<"0x"<< UC_unit << " ;" << endl;
Cpp << "#define UC_unit " << hex <<"0x"<< UC_unit <<  endl;
VB  << "public const UC_unit as long = " << UC_unit << " ;" << endl;
CS  << "   public const uint UC_count = " << hex <<"0x"<< UC_count << " ;" << endl;
Cpp << "#define UC_count " << hex <<"0x"<< UC_count <<  endl;
VB  << "public const UC_count as long = " << UC_count << " ;" << endl;
CS  << "   public const uint UC_percent = " << hex <<"0x"<< UC_percent << " ;" << endl;
Cpp << "#define UC_percent " << hex <<"0x"<< UC_percent <<  endl;
VB  << "public const UC_percent as long = " << UC_percent << " ;" << endl;
CS  << "   public const uint UC_decimal_percent = " << hex <<"0x"<< UC_decimal_percent << " ;" << endl;
Cpp << "#define UC_decimal_percent " << hex <<"0x"<< UC_decimal_percent <<  endl;
VB  << "public const UC_decimal_percent as long = " << UC_decimal_percent << " ;" << endl;
CS  << "   public const uint UC_index = " << hex <<"0x"<< UC_index << " ;" << endl;
Cpp << "#define UC_index " << hex <<"0x"<< UC_index <<  endl;
VB  << "public const UC_index as long = " << UC_index << " ;" << endl;
CS  << "   public const uint UC_adjustment = " << hex <<"0x"<< UC_adjustment << " ;" << endl;
Cpp << "#define UC_adjustment " << hex <<"0x"<< UC_adjustment <<  endl;
VB  << "public const UC_adjustment as long = " << UC_adjustment << " ;" << endl;
CS  << "   public const uint UC_ratio = " << hex <<"0x"<< UC_ratio << " ;" << endl;
Cpp << "#define UC_ratio " << hex <<"0x"<< UC_ratio <<  endl;
VB  << "public const UC_ratio as long = " << UC_ratio << " ;" << endl;
CS  << "   public const uint UC_fraction = " << hex <<"0x"<< UC_fraction << " ;" << endl;
Cpp << "#define UC_fraction " << hex <<"0x"<< UC_fraction <<  endl;
VB  << "public const UC_fraction as long = " << UC_fraction << " ;" << endl;
CS  << "   public const uint UC_probability = " << hex <<"0x"<< UC_probability << " ;" << endl;
Cpp << "#define UC_probability " << hex <<"0x"<< UC_probability <<  endl;
VB  << "public const UC_probability as long = " << UC_probability << " ;" << endl;
CS  << "   public const uint UC_pH = " << hex <<"0x"<< UC_pH << " ;" << endl;
Cpp << "#define UC_pH " << hex <<"0x"<< UC_pH <<  endl;
VB  << "public const UC_pH as long = " << UC_pH << " ;" << endl;
CS  << "   public const uint UT_time = " << hex <<"0x"<< UT_time << " ;" << endl;
Cpp << "#define UT_time " << hex <<"0x"<< UT_time <<  endl;
VB  << "public const UT_time as long = " << UT_time << " ;" << endl;
CS  << "   public const uint UT_date = " << hex <<"0x"<< UT_date << " ;" << endl;
Cpp << "#define UT_date " << hex <<"0x"<< UT_date <<  endl;
VB  << "public const UT_date as long = " << UT_date << " ;" << endl;
CS  << "   public const uint UT_day_of_year = " << hex <<"0x"<< UT_day_of_year << " ;" << endl;
Cpp << "#define UT_day_of_year " << hex <<"0x"<< UT_day_of_year <<  endl;
VB  << "public const UT_day_of_year as long = " << UT_day_of_year << " ;" << endl;
CS  << "   public const uint UT_sunday = " << hex <<"0x"<< UT_sunday << " ;" << endl;
Cpp << "#define UT_sunday " << hex <<"0x"<< UT_sunday <<  endl;
VB  << "public const UT_sunday as long = " << UT_sunday << " ;" << endl;
CS  << "   public const uint UT_monday = " << hex <<"0x"<< UT_monday << " ;" << endl;
Cpp << "#define UT_monday " << hex <<"0x"<< UT_monday <<  endl;
VB  << "public const UT_monday as long = " << UT_monday << " ;" << endl;
CS  << "   public const uint UT_tuesday = " << hex <<"0x"<< UT_tuesday << " ;" << endl;
Cpp << "#define UT_tuesday " << hex <<"0x"<< UT_tuesday <<  endl;
VB  << "public const UT_tuesday as long = " << UT_tuesday << " ;" << endl;
CS  << "   public const uint UT_wednesday = " << hex <<"0x"<< UT_wednesday << " ;" << endl;
Cpp << "#define UT_wednesday " << hex <<"0x"<< UT_wednesday <<  endl;
VB  << "public const UT_wednesday as long = " << UT_wednesday << " ;" << endl;
CS  << "   public const uint UT_thursday = " << hex <<"0x"<< UT_thursday << " ;" << endl;
Cpp << "#define UT_thursday " << hex <<"0x"<< UT_thursday <<  endl;
VB  << "public const UT_thursday as long = " << UT_thursday << " ;" << endl;
CS  << "   public const uint UT_friday = " << hex <<"0x"<< UT_friday << " ;" << endl;
Cpp << "#define UT_friday " << hex <<"0x"<< UT_friday <<  endl;
VB  << "public const UT_friday as long = " << UT_friday << " ;" << endl;
CS  << "   public const uint UT_saturday = " << hex <<"0x"<< UT_saturday << " ;" << endl;
Cpp << "#define UT_saturday " << hex <<"0x"<< UT_saturday <<  endl;
VB  << "public const UT_saturday as long = " << UT_saturday << " ;" << endl;
CS  << "   public const uint UT_day_of_month = " << hex <<"0x"<< UT_day_of_month << " ;" << endl;
Cpp << "#define UT_day_of_month " << hex <<"0x"<< UT_day_of_month <<  endl;
VB  << "public const UT_day_of_month as long = " << UT_day_of_month << " ;" << endl;
CS  << "   public const uint UT_day_of_month_1 = " << hex <<"0x"<< UT_day_of_month_1 << " ;" << endl;
Cpp << "#define UT_day_of_month_1 " << hex <<"0x"<< UT_day_of_month_1 <<  endl;
VB  << "public const UT_day_of_month_1 as long = " << UT_day_of_month_1 << " ;" << endl;
CS  << "   public const uint UT_day_of_month_31 = " << hex <<"0x"<< UT_day_of_month_31 << " ;" << endl;
Cpp << "#define UT_day_of_month_31 " << hex <<"0x"<< UT_day_of_month_31 <<  endl;
VB  << "public const UT_day_of_month_31 as long = " << UT_day_of_month_31 << " ;" << endl;
CS  << "   public const uint UT_week = " << hex <<"0x"<< UT_week << " ;" << endl;
Cpp << "#define UT_week " << hex <<"0x"<< UT_week <<  endl;
VB  << "public const UT_week as long = " << UT_week << " ;" << endl;
CS  << "   public const uint UT_fortnight = " << hex <<"0x"<< UT_fortnight << " ;" << endl;
Cpp << "#define UT_fortnight " << hex <<"0x"<< UT_fortnight <<  endl;
VB  << "public const UT_fortnight as long = " << UT_fortnight << " ;" << endl;
CS  << "   public const uint UT_month = " << hex <<"0x"<< UT_month << " ;" << endl;
Cpp << "#define UT_month " << hex <<"0x"<< UT_month <<  endl;
VB  << "public const UT_month as long = " << UT_month << " ;" << endl;
CS  << "   public const uint UT_january = " << hex <<"0x"<< UT_january << " ;" << endl;
Cpp << "#define UT_january " << hex <<"0x"<< UT_january <<  endl;
VB  << "public const UT_january as long = " << UT_january << " ;" << endl;
CS  << "   public const uint UT_february = " << hex <<"0x"<< UT_february << " ;" << endl;
Cpp << "#define UT_february " << hex <<"0x"<< UT_february <<  endl;
VB  << "public const UT_february as long = " << UT_february << " ;" << endl;
CS  << "   public const uint UT_march = " << hex <<"0x"<< UT_march << " ;" << endl;
Cpp << "#define UT_march " << hex <<"0x"<< UT_march <<  endl;
VB  << "public const UT_march as long = " << UT_march << " ;" << endl;
CS  << "   public const uint UT_april = " << hex <<"0x"<< UT_april << " ;" << endl;
Cpp << "#define UT_april " << hex <<"0x"<< UT_april <<  endl;
VB  << "public const UT_april as long = " << UT_april << " ;" << endl;
CS  << "   public const uint UT_may = " << hex <<"0x"<< UT_may << " ;" << endl;
Cpp << "#define UT_may " << hex <<"0x"<< UT_may <<  endl;
VB  << "public const UT_may as long = " << UT_may << " ;" << endl;
CS  << "   public const uint UT_june = " << hex <<"0x"<< UT_june << " ;" << endl;
Cpp << "#define UT_june " << hex <<"0x"<< UT_june <<  endl;
VB  << "public const UT_june as long = " << UT_june << " ;" << endl;
CS  << "   public const uint UT_july = " << hex <<"0x"<< UT_july << " ;" << endl;
Cpp << "#define UT_july " << hex <<"0x"<< UT_july <<  endl;
VB  << "public const UT_july as long = " << UT_july << " ;" << endl;
CS  << "   public const uint UT_august = " << hex <<"0x"<< UT_august << " ;" << endl;
Cpp << "#define UT_august " << hex <<"0x"<< UT_august <<  endl;
VB  << "public const UT_august as long = " << UT_august << " ;" << endl;
CS  << "   public const uint UT_september = " << hex <<"0x"<< UT_september << " ;" << endl;
Cpp << "#define UT_september " << hex <<"0x"<< UT_september <<  endl;
VB  << "public const UT_september as long = " << UT_september << " ;" << endl;
CS  << "   public const uint UT_october = " << hex <<"0x"<< UT_october << " ;" << endl;
Cpp << "#define UT_october " << hex <<"0x"<< UT_october <<  endl;
VB  << "public const UT_october as long = " << UT_october << " ;" << endl;
CS  << "   public const uint UT_november = " << hex <<"0x"<< UT_november << " ;" << endl;
Cpp << "#define UT_november " << hex <<"0x"<< UT_november <<  endl;
VB  << "public const UT_november as long = " << UT_november << " ;" << endl;
CS  << "   public const uint UT_december = " << hex <<"0x"<< UT_december << " ;" << endl;
Cpp << "#define UT_december " << hex <<"0x"<< UT_december <<  endl;
VB  << "public const UT_december as long = " << UT_december << " ;" << endl;
CS  << "   public const uint UT_quarter = " << hex <<"0x"<< UT_quarter << " ;" << endl;
Cpp << "#define UT_quarter " << hex <<"0x"<< UT_quarter <<  endl;
VB  << "public const UT_quarter as long = " << UT_quarter << " ;" << endl;
CS  << "   public const uint UT_quarter_1 = " << hex <<"0x"<< UT_quarter_1 << " ;" << endl;
Cpp << "#define UT_quarter_1 " << hex <<"0x"<< UT_quarter_1 <<  endl;
VB  << "public const UT_quarter_1 as long = " << UT_quarter_1 << " ;" << endl;
CS  << "   public const uint UT_quarter_2 = " << hex <<"0x"<< UT_quarter_2 << " ;" << endl;
Cpp << "#define UT_quarter_2 " << hex <<"0x"<< UT_quarter_2 <<  endl;
VB  << "public const UT_quarter_2 as long = " << UT_quarter_2 << " ;" << endl;
CS  << "   public const uint UT_quarter_3 = " << hex <<"0x"<< UT_quarter_3 << " ;" << endl;
Cpp << "#define UT_quarter_3 " << hex <<"0x"<< UT_quarter_3 <<  endl;
VB  << "public const UT_quarter_3 as long = " << UT_quarter_3 << " ;" << endl;
CS  << "   public const uint UT_quarter_4 = " << hex <<"0x"<< UT_quarter_4 << " ;" << endl;
Cpp << "#define UT_quarter_4 " << hex <<"0x"<< UT_quarter_4 <<  endl;
VB  << "public const UT_quarter_4 as long = " << UT_quarter_4 << " ;" << endl;
CS  << "   public const uint UT_trimester = " << hex <<"0x"<< UT_trimester << " ;" << endl;
Cpp << "#define UT_trimester " << hex <<"0x"<< UT_trimester <<  endl;
VB  << "public const UT_trimester as long = " << UT_trimester << " ;" << endl;
CS  << "   public const uint UT_trimester_1 = " << hex <<"0x"<< UT_trimester_1 << " ;" << endl;
Cpp << "#define UT_trimester_1 " << hex <<"0x"<< UT_trimester_1 <<  endl;
VB  << "public const UT_trimester_1 as long = " << UT_trimester_1 << " ;" << endl;
CS  << "   public const uint UT_trimester_2 = " << hex <<"0x"<< UT_trimester_2 << " ;" << endl;
Cpp << "#define UT_trimester_2 " << hex <<"0x"<< UT_trimester_2 <<  endl;
VB  << "public const UT_trimester_2 as long = " << UT_trimester_2 << " ;" << endl;
CS  << "   public const uint UT_trimester_3 = " << hex <<"0x"<< UT_trimester_3 << " ;" << endl;
Cpp << "#define UT_trimester_3 " << hex <<"0x"<< UT_trimester_3 <<  endl;
VB  << "public const UT_trimester_3 as long = " << UT_trimester_3 << " ;" << endl;
CS  << "   public const uint UT_biannum = " << hex <<"0x"<< UT_biannum << " ;" << endl;
Cpp << "#define UT_biannum " << hex <<"0x"<< UT_biannum <<  endl;
VB  << "public const UT_biannum as long = " << UT_biannum << " ;" << endl;
CS  << "   public const uint UT_biannum_1 = " << hex <<"0x"<< UT_biannum_1 << " ;" << endl;
Cpp << "#define UT_biannum_1 " << hex <<"0x"<< UT_biannum_1 <<  endl;
VB  << "public const UT_biannum_1 as long = " << UT_biannum_1 << " ;" << endl;
CS  << "   public const uint UT_biannum_2 = " << hex <<"0x"<< UT_biannum_2 << " ;" << endl;
Cpp << "#define UT_biannum_2 " << hex <<"0x"<< UT_biannum_2 <<  endl;
VB  << "public const UT_biannum_2 as long = " << UT_biannum_2 << " ;" << endl;
CS  << "   public const uint UT_0_seconds = " << hex <<"0x"<< UT_0_seconds << " ;" << endl;
Cpp << "#define UT_0_seconds " << hex <<"0x"<< UT_0_seconds <<  endl;
VB  << "public const UT_0_seconds as long = " << UT_0_seconds << " ;" << endl;
CS  << "   public const uint UT_1_second = " << hex <<"0x"<< UT_1_second << " ;" << endl;
Cpp << "#define UT_1_second " << hex <<"0x"<< UT_1_second <<  endl;
VB  << "public const UT_1_second as long = " << UT_1_second << " ;" << endl;
CS  << "   public const uint UT_30_seconds = " << hex <<"0x"<< UT_30_seconds << " ;" << endl;
Cpp << "#define UT_30_seconds " << hex <<"0x"<< UT_30_seconds <<  endl;
VB  << "public const UT_30_seconds as long = " << UT_30_seconds << " ;" << endl;
CS  << "   public const uint UT_60_seconds = " << hex <<"0x"<< UT_60_seconds << " ;" << endl;
Cpp << "#define UT_60_seconds " << hex <<"0x"<< UT_60_seconds <<  endl;
VB  << "public const UT_60_seconds as long = " << UT_60_seconds << " ;" << endl;
CS  << "   public const uint UT_0_minutes = " << hex <<"0x"<< UT_0_minutes << " ;" << endl;
Cpp << "#define UT_0_minutes " << hex <<"0x"<< UT_0_minutes <<  endl;
VB  << "public const UT_0_minutes as long = " << UT_0_minutes << " ;" << endl;
CS  << "   public const uint UT_1_minute = " << hex <<"0x"<< UT_1_minute << " ;" << endl;
Cpp << "#define UT_1_minute " << hex <<"0x"<< UT_1_minute <<  endl;
VB  << "public const UT_1_minute as long = " << UT_1_minute << " ;" << endl;
CS  << "   public const uint UT_10_minutes = " << hex <<"0x"<< UT_10_minutes << " ;" << endl;
Cpp << "#define UT_10_minutes " << hex <<"0x"<< UT_10_minutes <<  endl;
VB  << "public const UT_10_minutes as long = " << UT_10_minutes << " ;" << endl;
CS  << "   public const uint UT_15_minutes = " << hex <<"0x"<< UT_15_minutes << " ;" << endl;
Cpp << "#define UT_15_minutes " << hex <<"0x"<< UT_15_minutes <<  endl;
VB  << "public const UT_15_minutes as long = " << UT_15_minutes << " ;" << endl;
CS  << "   public const uint UT_30_minutes = " << hex <<"0x"<< UT_30_minutes << " ;" << endl;
Cpp << "#define UT_30_minutes " << hex <<"0x"<< UT_30_minutes <<  endl;
VB  << "public const UT_30_minutes as long = " << UT_30_minutes << " ;" << endl;
CS  << "   public const uint UT_half_hour = " << hex <<"0x"<< UT_half_hour << " ;" << endl;
Cpp << "#define UT_half_hour " << hex <<"0x"<< UT_half_hour <<  endl;
VB  << "public const UT_half_hour as long = " << UT_half_hour << " ;" << endl;
CS  << "   public const uint UT_60_minutes = " << hex <<"0x"<< UT_60_minutes << " ;" << endl;
Cpp << "#define UT_60_minutes " << hex <<"0x"<< UT_60_minutes <<  endl;
VB  << "public const UT_60_minutes as long = " << UT_60_minutes << " ;" << endl;
CS  << "   public const uint UT_0_hours = " << hex <<"0x"<< UT_0_hours << " ;" << endl;
Cpp << "#define UT_0_hours " << hex <<"0x"<< UT_0_hours <<  endl;
VB  << "public const UT_0_hours as long = " << UT_0_hours << " ;" << endl;
CS  << "   public const uint UT_1_hour = " << hex <<"0x"<< UT_1_hour << " ;" << endl;
Cpp << "#define UT_1_hour " << hex <<"0x"<< UT_1_hour <<  endl;
VB  << "public const UT_1_hour as long = " << UT_1_hour << " ;" << endl;
CS  << "   public const uint UT_24_hours = " << hex <<"0x"<< UT_24_hours << " ;" << endl;
Cpp << "#define UT_24_hours " << hex <<"0x"<< UT_24_hours <<  endl;
VB  << "public const UT_24_hours as long = " << UT_24_hours << " ;" << endl;
CS  << "   public const uint UT_second = " << hex <<"0x"<< UT_second << " ;" << endl;
Cpp << "#define UT_second " << hex <<"0x"<< UT_second <<  endl;
VB  << "public const UT_second as long = " << UT_second << " ;" << endl;
CS  << "   public const uint UT_second = " << hex <<"0x"<< UT_second << " ;" << endl;
Cpp << "#define UT_second " << hex <<"0x"<< UT_second <<  endl;
VB  << "public const UT_second as long = " << UT_second << " ;" << endl;
CS  << "   public const uint UT_minute = " << hex <<"0x"<< UT_minute << " ;" << endl;
Cpp << "#define UT_minute " << hex <<"0x"<< UT_minute <<  endl;
VB  << "public const UT_minute as long = " << UT_minute << " ;" << endl;
CS  << "   public const uint UT_hour = " << hex <<"0x"<< UT_hour << " ;" << endl;
Cpp << "#define UT_hour " << hex <<"0x"<< UT_hour <<  endl;
VB  << "public const UT_hour as long = " << UT_hour << " ;" << endl;
CS  << "   public const uint UT_day = " << hex <<"0x"<< UT_day << " ;" << endl;
Cpp << "#define UT_day " << hex <<"0x"<< UT_day <<  endl;
VB  << "public const UT_day as long = " << UT_day << " ;" << endl;
CS  << "   public const uint UT_year = " << hex <<"0x"<< UT_year << " ;" << endl;
Cpp << "#define UT_year " << hex <<"0x"<< UT_year <<  endl;
VB  << "public const UT_year as long = " << UT_year << " ;" << endl;
CS  << "   public const uint UT_decade = " << hex <<"0x"<< UT_decade << " ;" << endl;
Cpp << "#define UT_decade " << hex <<"0x"<< UT_decade <<  endl;
VB  << "public const UT_decade as long = " << UT_decade << " ;" << endl;
CS  << "   public const uint UT_century = " << hex <<"0x"<< UT_century << " ;" << endl;
Cpp << "#define UT_century " << hex <<"0x"<< UT_century <<  endl;
VB  << "public const UT_century as long = " << UT_century << " ;" << endl;
CS  << "   public const uint UT_millenium = " << hex <<"0x"<< UT_millenium << " ;" << endl;
Cpp << "#define UT_millenium " << hex <<"0x"<< UT_millenium <<  endl;
VB  << "public const UT_millenium as long = " << UT_millenium << " ;" << endl;
CS  << "   public const uint UC_celcius = " << hex <<"0x"<< UC_celcius << " ;" << endl;
Cpp << "#define UC_celcius " << hex <<"0x"<< UC_celcius <<  endl;
VB  << "public const UC_celcius as long = " << UC_celcius << " ;" << endl;
CS  << "   public const uint UE_Farenheit = " << hex <<"0x"<< UE_Farenheit << " ;" << endl;
Cpp << "#define UE_Farenheit " << hex <<"0x"<< UE_Farenheit <<  endl;
VB  << "public const UE_Farenheit as long = " << UE_Farenheit << " ;" << endl;
CS  << "   public const uint UC_kelvin = " << hex <<"0x"<< UC_kelvin << " ;" << endl;
Cpp << "#define UC_kelvin " << hex <<"0x"<< UC_kelvin <<  endl;
VB  << "public const UC_kelvin as long = " << UC_kelvin << " ;" << endl;
CS  << "   public const uint UE_Rankine = " << hex <<"0x"<< UE_Rankine << " ;" << endl;
Cpp << "#define UE_Rankine " << hex <<"0x"<< UE_Rankine <<  endl;
VB  << "public const UE_Rankine as long = " << UE_Rankine << " ;" << endl;
CS  << "   public const uint UC_celcius_degree_days = " << hex <<"0x"<< UC_celcius_degree_days << " ;" << endl;
Cpp << "#define UC_celcius_degree_days " << hex <<"0x"<< UC_celcius_degree_days <<  endl;
VB  << "public const UC_celcius_degree_days as long = " << UC_celcius_degree_days << " ;" << endl;
CS  << "   public const uint UE_Farenheit_degree_days = " << hex <<"0x"<< UE_Farenheit_degree_days << " ;" << endl;
Cpp << "#define UE_Farenheit_degree_days " << hex <<"0x"<< UE_Farenheit_degree_days <<  endl;
VB  << "public const UE_Farenheit_degree_days as long = " << UE_Farenheit_degree_days << " ;" << endl;
CS  << "   public const uint UC_Equivelent_weight = " << hex <<"0x"<< UC_Equivelent_weight << " ;" << endl;
Cpp << "#define UC_Equivelent_weight " << hex <<"0x"<< UC_Equivelent_weight <<  endl;
VB  << "public const UC_Equivelent_weight as long = " << UC_Equivelent_weight << " ;" << endl;
CS  << "   public const uint UC_mEq = " << hex <<"0x"<< UC_mEq << " ;" << endl;
Cpp << "#define UC_mEq " << hex <<"0x"<< UC_mEq <<  endl;
VB  << "public const UC_mEq as long = " << UC_mEq << " ;" << endl;
CS  << "   public const uint UC_mole = " << hex <<"0x"<< UC_mole << " ;" << endl;
Cpp << "#define UC_mole " << hex <<"0x"<< UC_mole <<  endl;
VB  << "public const UC_mole as long = " << UC_mole << " ;" << endl;
CS  << "   public const uint UC_nanogram_mass = " << hex <<"0x"<< UC_nanogram_mass << " ;" << endl;
Cpp << "#define UC_nanogram_mass " << hex <<"0x"<< UC_nanogram_mass <<  endl;
VB  << "public const UC_nanogram_mass as long = " << UC_nanogram_mass << " ;" << endl;
CS  << "   public const uint UC_microgram_mass = " << hex <<"0x"<< UC_microgram_mass << " ;" << endl;
Cpp << "#define UC_microgram_mass " << hex <<"0x"<< UC_microgram_mass <<  endl;
VB  << "public const UC_microgram_mass as long = " << UC_microgram_mass << " ;" << endl;
CS  << "   public const uint UC_mg_mass = " << hex <<"0x"<< UC_mg_mass << " ;" << endl;
Cpp << "#define UC_mg_mass " << hex <<"0x"<< UC_mg_mass <<  endl;
VB  << "public const UC_mg_mass as long = " << UC_mg_mass << " ;" << endl;
CS  << "   public const uint UC_cg_mass = " << hex <<"0x"<< UC_cg_mass << " ;" << endl;
Cpp << "#define UC_cg_mass " << hex <<"0x"<< UC_cg_mass <<  endl;
VB  << "public const UC_cg_mass as long = " << UC_cg_mass << " ;" << endl;
CS  << "   public const uint UC_dg_mass = " << hex <<"0x"<< UC_dg_mass << " ;" << endl;
Cpp << "#define UC_dg_mass " << hex <<"0x"<< UC_dg_mass <<  endl;
VB  << "public const UC_dg_mass as long = " << UC_dg_mass << " ;" << endl;
CS  << "   public const uint UC_gram_mass = " << hex <<"0x"<< UC_gram_mass << " ;" << endl;
Cpp << "#define UC_gram_mass " << hex <<"0x"<< UC_gram_mass <<  endl;
VB  << "public const UC_gram_mass as long = " << UC_gram_mass << " ;" << endl;
CS  << "   public const uint UC_g = " << hex <<"0x"<< UC_g << " ;" << endl;
Cpp << "#define UC_g " << hex <<"0x"<< UC_g <<  endl;
VB  << "public const UC_g as long = " << UC_g << " ;" << endl;
CS  << "   public const uint UC_Dg_mass = " << hex <<"0x"<< UC_Dg_mass << " ;" << endl;
Cpp << "#define UC_Dg_mass " << hex <<"0x"<< UC_Dg_mass <<  endl;
VB  << "public const UC_Dg_mass as long = " << UC_Dg_mass << " ;" << endl;
CS  << "   public const uint UC_hg_mass = " << hex <<"0x"<< UC_hg_mass << " ;" << endl;
Cpp << "#define UC_hg_mass " << hex <<"0x"<< UC_hg_mass <<  endl;
VB  << "public const UC_hg_mass as long = " << UC_hg_mass << " ;" << endl;
CS  << "   public const uint UC_kg_mass = " << hex <<"0x"<< UC_kg_mass << " ;" << endl;
Cpp << "#define UC_kg_mass " << hex <<"0x"<< UC_kg_mass <<  endl;
VB  << "public const UC_kg_mass as long = " << UC_kg_mass << " ;" << endl;
CS  << "   public const uint UC_tonne_mass = " << hex <<"0x"<< UC_tonne_mass << " ;" << endl;
Cpp << "#define UC_tonne_mass " << hex <<"0x"<< UC_tonne_mass <<  endl;
VB  << "public const UC_tonne_mass as long = " << UC_tonne_mass << " ;" << endl;
CS  << "   public const uint UE_grain = " << hex <<"0x"<< UE_grain << " ;" << endl;
Cpp << "#define UE_grain " << hex <<"0x"<< UE_grain <<  endl;
VB  << "public const UE_grain as long = " << UE_grain << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_dram = " << hex <<"0x"<< UE_avoirdupois_dram << " ;" << endl;
Cpp << "#define UE_avoirdupois_dram " << hex <<"0x"<< UE_avoirdupois_dram <<  endl;
VB  << "public const UE_avoirdupois_dram as long = " << UE_avoirdupois_dram << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_ounce = " << hex <<"0x"<< UE_avoirdupois_ounce << " ;" << endl;
Cpp << "#define UE_avoirdupois_ounce " << hex <<"0x"<< UE_avoirdupois_ounce <<  endl;
VB  << "public const UE_avoirdupois_ounce as long = " << UE_avoirdupois_ounce << " ;" << endl;
CS  << "   public const uint UE_avoiddupois_pound = " << hex <<"0x"<< UE_avoiddupois_pound << " ;" << endl;
Cpp << "#define UE_avoiddupois_pound " << hex <<"0x"<< UE_avoiddupois_pound <<  endl;
VB  << "public const UE_avoiddupois_pound as long = " << UE_avoiddupois_pound << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_pound = " << hex <<"0x"<< UE_avoirdupois_pound << " ;" << endl;
Cpp << "#define UE_avoirdupois_pound " << hex <<"0x"<< UE_avoirdupois_pound <<  endl;
VB  << "public const UE_avoirdupois_pound as long = " << UE_avoirdupois_pound << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_clove = " << hex <<"0x"<< UE_avoirdupois_clove << " ;" << endl;
Cpp << "#define UE_avoirdupois_clove " << hex <<"0x"<< UE_avoirdupois_clove <<  endl;
VB  << "public const UE_avoirdupois_clove as long = " << UE_avoirdupois_clove << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_butchers_stone = " << hex <<"0x"<< UE_avoirdupois_butchers_stone << " ;" << endl;
Cpp << "#define UE_avoirdupois_butchers_stone " << hex <<"0x"<< UE_avoirdupois_butchers_stone <<  endl;
VB  << "public const UE_avoirdupois_butchers_stone as long = " << UE_avoirdupois_butchers_stone << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_stone = " << hex <<"0x"<< UE_avoirdupois_stone << " ;" << endl;
Cpp << "#define UE_avoirdupois_stone " << hex <<"0x"<< UE_avoirdupois_stone <<  endl;
VB  << "public const UE_avoirdupois_stone as long = " << UE_avoirdupois_stone << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_tod = " << hex <<"0x"<< UE_avoirdupois_tod << " ;" << endl;
Cpp << "#define UE_avoirdupois_tod " << hex <<"0x"<< UE_avoirdupois_tod <<  endl;
VB  << "public const UE_avoirdupois_tod as long = " << UE_avoirdupois_tod << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_quarter = " << hex <<"0x"<< UE_avoirdupois_quarter << " ;" << endl;
Cpp << "#define UE_avoirdupois_quarter " << hex <<"0x"<< UE_avoirdupois_quarter <<  endl;
VB  << "public const UE_avoirdupois_quarter as long = " << UE_avoirdupois_quarter << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_hundredweight_US = " << hex <<"0x"<< UE_avoirdupois_hundredweight_US << " ;" << endl;
Cpp << "#define UE_avoirdupois_hundredweight_US " << hex <<"0x"<< UE_avoirdupois_hundredweight_US <<  endl;
VB  << "public const UE_avoirdupois_hundredweight_US as long = " << UE_avoirdupois_hundredweight_US << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_hundredweight_Imperial = " << hex <<"0x"<< UE_avoirdupois_hundredweight_Imperial << " ;" << endl;
Cpp << "#define UE_avoirdupois_hundredweight_Imperial " << hex <<"0x"<< UE_avoirdupois_hundredweight_Imperial <<  endl;
VB  << "public const UE_avoirdupois_hundredweight_Imperial as long = " << UE_avoirdupois_hundredweight_Imperial << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_sack = " << hex <<"0x"<< UE_avoirdupois_sack << " ;" << endl;
Cpp << "#define UE_avoirdupois_sack " << hex <<"0x"<< UE_avoirdupois_sack <<  endl;
VB  << "public const UE_avoirdupois_sack as long = " << UE_avoirdupois_sack << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_kip = " << hex <<"0x"<< UE_avoirdupois_kip << " ;" << endl;
Cpp << "#define UE_avoirdupois_kip " << hex <<"0x"<< UE_avoirdupois_kip <<  endl;
VB  << "public const UE_avoirdupois_kip as long = " << UE_avoirdupois_kip << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_ton_US = " << hex <<"0x"<< UE_avoirdupois_ton_US << " ;" << endl;
Cpp << "#define UE_avoirdupois_ton_US " << hex <<"0x"<< UE_avoirdupois_ton_US <<  endl;
VB  << "public const UE_avoirdupois_ton_US as long = " << UE_avoirdupois_ton_US << " ;" << endl;
CS  << "   public const uint UE_avoirdupois_ton_Imperial = " << hex <<"0x"<< UE_avoirdupois_ton_Imperial << " ;" << endl;
Cpp << "#define UE_avoirdupois_ton_Imperial " << hex <<"0x"<< UE_avoirdupois_ton_Imperial <<  endl;
VB  << "public const UE_avoirdupois_ton_Imperial as long = " << UE_avoirdupois_ton_Imperial << " ;" << endl;
CS  << "   public const uint UE_tower_penny = " << hex <<"0x"<< UE_tower_penny << " ;" << endl;
Cpp << "#define UE_tower_penny " << hex <<"0x"<< UE_tower_penny <<  endl;
VB  << "public const UE_tower_penny as long = " << UE_tower_penny << " ;" << endl;
CS  << "   public const uint UE_tower_pound = " << hex <<"0x"<< UE_tower_pound << " ;" << endl;
Cpp << "#define UE_tower_pound " << hex <<"0x"<< UE_tower_pound <<  endl;
VB  << "public const UE_tower_pound as long = " << UE_tower_pound << " ;" << endl;
CS  << "   public const uint UE_trade_pound = " << hex <<"0x"<< UE_trade_pound << " ;" << endl;
Cpp << "#define UE_trade_pound " << hex <<"0x"<< UE_trade_pound <<  endl;
VB  << "public const UE_trade_pound as long = " << UE_trade_pound << " ;" << endl;
CS  << "   public const uint UE_trade_stone = " << hex <<"0x"<< UE_trade_stone << " ;" << endl;
Cpp << "#define UE_trade_stone " << hex <<"0x"<< UE_trade_stone <<  endl;
VB  << "public const UE_trade_stone as long = " << UE_trade_stone << " ;" << endl;
CS  << "   public const uint UE_troy_scruple = " << hex <<"0x"<< UE_troy_scruple << " ;" << endl;
Cpp << "#define UE_troy_scruple " << hex <<"0x"<< UE_troy_scruple <<  endl;
VB  << "public const UE_troy_scruple as long = " << UE_troy_scruple << " ;" << endl;
CS  << "   public const uint UE_troy_pennyweight = " << hex <<"0x"<< UE_troy_pennyweight << " ;" << endl;
Cpp << "#define UE_troy_pennyweight " << hex <<"0x"<< UE_troy_pennyweight <<  endl;
VB  << "public const UE_troy_pennyweight as long = " << UE_troy_pennyweight << " ;" << endl;
CS  << "   public const uint UE_troy_dram = " << hex <<"0x"<< UE_troy_dram << " ;" << endl;
Cpp << "#define UE_troy_dram " << hex <<"0x"<< UE_troy_dram <<  endl;
VB  << "public const UE_troy_dram as long = " << UE_troy_dram << " ;" << endl;
CS  << "   public const uint UE_troy_ounce = " << hex <<"0x"<< UE_troy_ounce << " ;" << endl;
Cpp << "#define UE_troy_ounce " << hex <<"0x"<< UE_troy_ounce <<  endl;
VB  << "public const UE_troy_ounce as long = " << UE_troy_ounce << " ;" << endl;
CS  << "   public const uint UE_troy_pound = " << hex <<"0x"<< UE_troy_pound << " ;" << endl;
Cpp << "#define UE_troy_pound " << hex <<"0x"<< UE_troy_pound <<  endl;
VB  << "public const UE_troy_pound as long = " << UE_troy_pound << " ;" << endl;
CS  << "   public const uint UE_wool_pound = " << hex <<"0x"<< UE_wool_pound << " ;" << endl;
Cpp << "#define UE_wool_pound " << hex <<"0x"<< UE_wool_pound <<  endl;
VB  << "public const UE_wool_pound as long = " << UE_wool_pound << " ;" << endl;
CS  << "   public const uint UE_wool_clove = " << hex <<"0x"<< UE_wool_clove << " ;" << endl;
Cpp << "#define UE_wool_clove " << hex <<"0x"<< UE_wool_clove <<  endl;
VB  << "public const UE_wool_clove as long = " << UE_wool_clove << " ;" << endl;
CS  << "   public const uint UE_wool_stone = " << hex <<"0x"<< UE_wool_stone << " ;" << endl;
Cpp << "#define UE_wool_stone " << hex <<"0x"<< UE_wool_stone <<  endl;
VB  << "public const UE_wool_stone as long = " << UE_wool_stone << " ;" << endl;
CS  << "   public const uint UE_wool_tod = " << hex <<"0x"<< UE_wool_tod << " ;" << endl;
Cpp << "#define UE_wool_tod " << hex <<"0x"<< UE_wool_tod <<  endl;
VB  << "public const UE_wool_tod as long = " << UE_wool_tod << " ;" << endl;
CS  << "   public const uint UC_candela = " << hex <<"0x"<< UC_candela << " ;" << endl;
Cpp << "#define UC_candela " << hex <<"0x"<< UC_candela <<  endl;
VB  << "public const UC_candela as long = " << UC_candela << " ;" << endl;
CS  << "   public const uint UC_lumen = " << hex <<"0x"<< UC_lumen << " ;" << endl;
Cpp << "#define UC_lumen " << hex <<"0x"<< UC_lumen <<  endl;
VB  << "public const UC_lumen as long = " << UC_lumen << " ;" << endl;
CS  << "   public const uint UC_lux = " << hex <<"0x"<< UC_lux << " ;" << endl;
Cpp << "#define UC_lux " << hex <<"0x"<< UC_lux <<  endl;
VB  << "public const UC_lux as long = " << UC_lux << " ;" << endl;
CS  << "   public const uint UC_kilo_lux = " << hex <<"0x"<< UC_kilo_lux << " ;" << endl;
Cpp << "#define UC_kilo_lux " << hex <<"0x"<< UC_kilo_lux <<  endl;
VB  << "public const UC_kilo_lux as long = " << UC_kilo_lux << " ;" << endl;
CS  << "   public const uint UC_phot = " << hex <<"0x"<< UC_phot << " ;" << endl;
Cpp << "#define UC_phot " << hex <<"0x"<< UC_phot <<  endl;
VB  << "public const UC_phot as long = " << UC_phot << " ;" << endl;
CS  << "   public const uint UC_stilb = " << hex <<"0x"<< UC_stilb << " ;" << endl;
Cpp << "#define UC_stilb " << hex <<"0x"<< UC_stilb <<  endl;
VB  << "public const UC_stilb as long = " << UC_stilb << " ;" << endl;
CS  << "   public const uint UC_length = " << hex <<"0x"<< UC_length << " ;" << endl;
Cpp << "#define UC_length " << hex <<"0x"<< UC_length <<  endl;
VB  << "public const UC_length as long = " << UC_length << " ;" << endl;
CS  << "   public const uint UC_meter = " << hex <<"0x"<< UC_meter << " ;" << endl;
Cpp << "#define UC_meter " << hex <<"0x"<< UC_meter <<  endl;
VB  << "public const UC_meter as long = " << UC_meter << " ;" << endl;
CS  << "   public const uint UC_km = " << hex <<"0x"<< UC_km << " ;" << endl;
Cpp << "#define UC_km " << hex <<"0x"<< UC_km <<  endl;
VB  << "public const UC_km as long = " << UC_km << " ;" << endl;
CS  << "   public const uint UC_m = " << hex <<"0x"<< UC_m << " ;" << endl;
Cpp << "#define UC_m " << hex <<"0x"<< UC_m <<  endl;
VB  << "public const UC_m as long = " << UC_m << " ;" << endl;
CS  << "   public const uint UC_cm = " << hex <<"0x"<< UC_cm << " ;" << endl;
Cpp << "#define UC_cm " << hex <<"0x"<< UC_cm <<  endl;
VB  << "public const UC_cm as long = " << UC_cm << " ;" << endl;
CS  << "   public const uint UC_mm = " << hex <<"0x"<< UC_mm << " ;" << endl;
Cpp << "#define UC_mm " << hex <<"0x"<< UC_mm <<  endl;
VB  << "public const UC_mm as long = " << UC_mm << " ;" << endl;
CS  << "   public const uint UC_angstrom = " << hex <<"0x"<< UC_angstrom << " ;" << endl;
Cpp << "#define UC_angstrom " << hex <<"0x"<< UC_angstrom <<  endl;
VB  << "public const UC_angstrom as long = " << UC_angstrom << " ;" << endl;
CS  << "   public const uint UC_fermi = " << hex <<"0x"<< UC_fermi << " ;" << endl;
Cpp << "#define UC_fermi " << hex <<"0x"<< UC_fermi <<  endl;
VB  << "public const UC_fermi as long = " << UC_fermi << " ;" << endl;
CS  << "   public const uint UE_inch = " << hex <<"0x"<< UE_inch << " ;" << endl;
Cpp << "#define UE_inch " << hex <<"0x"<< UE_inch <<  endl;
VB  << "public const UE_inch as long = " << UE_inch << " ;" << endl;
CS  << "   public const uint UE_nail = " << hex <<"0x"<< UE_nail << " ;" << endl;
Cpp << "#define UE_nail " << hex <<"0x"<< UE_nail <<  endl;
VB  << "public const UE_nail as long = " << UE_nail << " ;" << endl;
CS  << "   public const uint UE_hand = " << hex <<"0x"<< UE_hand << " ;" << endl;
Cpp << "#define UE_hand " << hex <<"0x"<< UE_hand <<  endl;
VB  << "public const UE_hand as long = " << UE_hand << " ;" << endl;
CS  << "   public const uint UE_link = " << hex <<"0x"<< UE_link << " ;" << endl;
Cpp << "#define UE_link " << hex <<"0x"<< UE_link <<  endl;
VB  << "public const UE_link as long = " << UE_link << " ;" << endl;
CS  << "   public const uint UE_foot = " << hex <<"0x"<< UE_foot << " ;" << endl;
Cpp << "#define UE_foot " << hex <<"0x"<< UE_foot <<  endl;
VB  << "public const UE_foot as long = " << UE_foot << " ;" << endl;
CS  << "   public const uint UE_yard = " << hex <<"0x"<< UE_yard << " ;" << endl;
Cpp << "#define UE_yard " << hex <<"0x"<< UE_yard <<  endl;
VB  << "public const UE_yard as long = " << UE_yard << " ;" << endl;
CS  << "   public const uint UE_rod = " << hex <<"0x"<< UE_rod << " ;" << endl;
Cpp << "#define UE_rod " << hex <<"0x"<< UE_rod <<  endl;
VB  << "public const UE_rod as long = " << UE_rod << " ;" << endl;
CS  << "   public const uint UE_pole = " << hex <<"0x"<< UE_pole << " ;" << endl;
Cpp << "#define UE_pole " << hex <<"0x"<< UE_pole <<  endl;
VB  << "public const UE_pole as long = " << UE_pole << " ;" << endl;
CS  << "   public const uint UE_perch = " << hex <<"0x"<< UE_perch << " ;" << endl;
Cpp << "#define UE_perch " << hex <<"0x"<< UE_perch <<  endl;
VB  << "public const UE_perch as long = " << UE_perch << " ;" << endl;
CS  << "   public const uint UE_lugg = " << hex <<"0x"<< UE_lugg << " ;" << endl;
Cpp << "#define UE_lugg " << hex <<"0x"<< UE_lugg <<  endl;
VB  << "public const UE_lugg as long = " << UE_lugg << " ;" << endl;
CS  << "   public const uint UE_fathom = " << hex <<"0x"<< UE_fathom << " ;" << endl;
Cpp << "#define UE_fathom " << hex <<"0x"<< UE_fathom <<  endl;
VB  << "public const UE_fathom as long = " << UE_fathom << " ;" << endl;
CS  << "   public const uint UE_chain = " << hex <<"0x"<< UE_chain << " ;" << endl;
Cpp << "#define UE_chain " << hex <<"0x"<< UE_chain <<  endl;
VB  << "public const UE_chain as long = " << UE_chain << " ;" << endl;
CS  << "   public const uint UE_furlong = " << hex <<"0x"<< UE_furlong << " ;" << endl;
Cpp << "#define UE_furlong " << hex <<"0x"<< UE_furlong <<  endl;
VB  << "public const UE_furlong as long = " << UE_furlong << " ;" << endl;
CS  << "   public const uint UE_statute_mile = " << hex <<"0x"<< UE_statute_mile << " ;" << endl;
Cpp << "#define UE_statute_mile " << hex <<"0x"<< UE_statute_mile <<  endl;
VB  << "public const UE_statute_mile as long = " << UE_statute_mile << " ;" << endl;
CS  << "   public const uint UE_nautical_mile_modern = " << hex <<"0x"<< UE_nautical_mile_modern << " ;" << endl;
Cpp << "#define UE_nautical_mile_modern " << hex <<"0x"<< UE_nautical_mile_modern <<  endl;
VB  << "public const UE_nautical_mile_modern as long = " << UE_nautical_mile_modern << " ;" << endl;
CS  << "   public const uint UE_nautical_mile = " << hex <<"0x"<< UE_nautical_mile << " ;" << endl;
Cpp << "#define UE_nautical_mile " << hex <<"0x"<< UE_nautical_mile <<  endl;
VB  << "public const UE_nautical_mile as long = " << UE_nautical_mile << " ;" << endl;
CS  << "   public const uint UC_square_meter_flat_area_obs = " << hex <<"0x"<< UC_square_meter_flat_area_obs << " ;" << endl;
Cpp << "#define UC_square_meter_flat_area_obs " << hex <<"0x"<< UC_square_meter_flat_area_obs <<  endl;
VB  << "public const UC_square_meter_flat_area_obs as long = " << UC_square_meter_flat_area_obs << " ;" << endl;
CS  << "   public const uint UC_square_meter_area = " << hex <<"0x"<< UC_square_meter_area << " ;" << endl;
Cpp << "#define UC_square_meter_area " << hex <<"0x"<< UC_square_meter_area <<  endl;
VB  << "public const UC_square_meter_area as long = " << UC_square_meter_area << " ;" << endl;
CS  << "   public const uint UC_square_m_area = " << hex <<"0x"<< UC_square_m_area << " ;" << endl;
Cpp << "#define UC_square_m_area " << hex <<"0x"<< UC_square_m_area <<  endl;
VB  << "public const UC_square_m_area as long = " << UC_square_m_area << " ;" << endl;
CS  << "   public const uint UC_square_cm_area = " << hex <<"0x"<< UC_square_cm_area << " ;" << endl;
Cpp << "#define UC_square_cm_area " << hex <<"0x"<< UC_square_cm_area <<  endl;
VB  << "public const UC_square_cm_area as long = " << UC_square_cm_area << " ;" << endl;
CS  << "   public const uint UC_are = " << hex <<"0x"<< UC_are << " ;" << endl;
Cpp << "#define UC_are " << hex <<"0x"<< UC_are <<  endl;
VB  << "public const UC_are as long = " << UC_are << " ;" << endl;
CS  << "   public const uint UC_hectare = " << hex <<"0x"<< UC_hectare << " ;" << endl;
Cpp << "#define UC_hectare " << hex <<"0x"<< UC_hectare <<  endl;
VB  << "public const UC_hectare as long = " << UC_hectare << " ;" << endl;
CS  << "   public const uint UE_acre = " << hex <<"0x"<< UE_acre << " ;" << endl;
Cpp << "#define UE_acre " << hex <<"0x"<< UE_acre <<  endl;
VB  << "public const UE_acre as long = " << UE_acre << " ;" << endl;
CS  << "   public const uint UE_rood = " << hex <<"0x"<< UE_rood << " ;" << endl;
Cpp << "#define UE_rood " << hex <<"0x"<< UE_rood <<  endl;
VB  << "public const UE_rood as long = " << UE_rood << " ;" << endl;
CS  << "   public const uint UE_arpent_area = " << hex <<"0x"<< UE_arpent_area << " ;" << endl;
Cpp << "#define UE_arpent_area " << hex <<"0x"<< UE_arpent_area <<  endl;
VB  << "public const UE_arpent_area as long = " << UE_arpent_area << " ;" << endl;
CS  << "   public const uint UE_virgate = " << hex <<"0x"<< UE_virgate << " ;" << endl;
Cpp << "#define UE_virgate " << hex <<"0x"<< UE_virgate <<  endl;
VB  << "public const UE_virgate as long = " << UE_virgate << " ;" << endl;
CS  << "   public const uint UE_hide = " << hex <<"0x"<< UE_hide << " ;" << endl;
Cpp << "#define UE_hide " << hex <<"0x"<< UE_hide <<  endl;
VB  << "public const UE_hide as long = " << UE_hide << " ;" << endl;
CS  << "   public const uint UE_morgen_scandinavian = " << hex <<"0x"<< UE_morgen_scandinavian << " ;" << endl;
Cpp << "#define UE_morgen_scandinavian " << hex <<"0x"<< UE_morgen_scandinavian <<  endl;
VB  << "public const UE_morgen_scandinavian as long = " << UE_morgen_scandinavian << " ;" << endl;
CS  << "   public const uint UE_morgen_prussian = " << hex <<"0x"<< UE_morgen_prussian << " ;" << endl;
Cpp << "#define UE_morgen_prussian " << hex <<"0x"<< UE_morgen_prussian <<  endl;
VB  << "public const UE_morgen_prussian as long = " << UE_morgen_prussian << " ;" << endl;
CS  << "   public const uint UE_morgen_dutch = " << hex <<"0x"<< UE_morgen_dutch << " ;" << endl;
Cpp << "#define UE_morgen_dutch " << hex <<"0x"<< UE_morgen_dutch <<  endl;
VB  << "public const UE_morgen_dutch as long = " << UE_morgen_dutch << " ;" << endl;
CS  << "   public const uint UE_morgen_south_african = " << hex <<"0x"<< UE_morgen_south_african << " ;" << endl;
Cpp << "#define UE_morgen_south_african " << hex <<"0x"<< UE_morgen_south_african <<  endl;
VB  << "public const UE_morgen_south_african as long = " << UE_morgen_south_african << " ;" << endl;
CS  << "   public const uint UC_cubic_meter_volume = " << hex <<"0x"<< UC_cubic_meter_volume << " ;" << endl;
Cpp << "#define UC_cubic_meter_volume " << hex <<"0x"<< UC_cubic_meter_volume <<  endl;
VB  << "public const UC_cubic_meter_volume as long = " << UC_cubic_meter_volume << " ;" << endl;
CS  << "   public const uint UC_liter = " << hex <<"0x"<< UC_liter << " ;" << endl;
Cpp << "#define UC_liter " << hex <<"0x"<< UC_liter <<  endl;
VB  << "public const UC_liter as long = " << UC_liter << " ;" << endl;
CS  << "   public const uint UC_ml = " << hex <<"0x"<< UC_ml << " ;" << endl;
Cpp << "#define UC_ml " << hex <<"0x"<< UC_ml <<  endl;
VB  << "public const UC_ml as long = " << UC_ml << " ;" << endl;
CS  << "   public const uint UE_minim = " << hex <<"0x"<< UE_minim << " ;" << endl;
Cpp << "#define UE_minim " << hex <<"0x"<< UE_minim <<  endl;
VB  << "public const UE_minim as long = " << UE_minim << " ;" << endl;
CS  << "   public const uint UE_drachm = " << hex <<"0x"<< UE_drachm << " ;" << endl;
Cpp << "#define UE_drachm " << hex <<"0x"<< UE_drachm <<  endl;
VB  << "public const UE_drachm as long = " << UE_drachm << " ;" << endl;
CS  << "   public const uint UE_ounce = " << hex <<"0x"<< UE_ounce << " ;" << endl;
Cpp << "#define UE_ounce " << hex <<"0x"<< UE_ounce <<  endl;
VB  << "public const UE_ounce as long = " << UE_ounce << " ;" << endl;
CS  << "   public const uint UE_gill = " << hex <<"0x"<< UE_gill << " ;" << endl;
Cpp << "#define UE_gill " << hex <<"0x"<< UE_gill <<  endl;
VB  << "public const UE_gill as long = " << UE_gill << " ;" << endl;
CS  << "   public const uint UE_mutchkin = " << hex <<"0x"<< UE_mutchkin << " ;" << endl;
Cpp << "#define UE_mutchkin " << hex <<"0x"<< UE_mutchkin <<  endl;
VB  << "public const UE_mutchkin as long = " << UE_mutchkin << " ;" << endl;
CS  << "   public const uint UE_pint = " << hex <<"0x"<< UE_pint << " ;" << endl;
Cpp << "#define UE_pint " << hex <<"0x"<< UE_pint <<  endl;
VB  << "public const UE_pint as long = " << UE_pint << " ;" << endl;
CS  << "   public const uint UE_fifth = " << hex <<"0x"<< UE_fifth << " ;" << endl;
Cpp << "#define UE_fifth " << hex <<"0x"<< UE_fifth <<  endl;
VB  << "public const UE_fifth as long = " << UE_fifth << " ;" << endl;
CS  << "   public const uint UE_quart = " << hex <<"0x"<< UE_quart << " ;" << endl;
Cpp << "#define UE_quart " << hex <<"0x"<< UE_quart <<  endl;
VB  << "public const UE_quart as long = " << UE_quart << " ;" << endl;
CS  << "   public const uint UE_gallon = " << hex <<"0x"<< UE_gallon << " ;" << endl;
Cpp << "#define UE_gallon " << hex <<"0x"<< UE_gallon <<  endl;
VB  << "public const UE_gallon as long = " << UE_gallon << " ;" << endl;
CS  << "   public const uint UE_peck = " << hex <<"0x"<< UE_peck << " ;" << endl;
Cpp << "#define UE_peck " << hex <<"0x"<< UE_peck <<  endl;
VB  << "public const UE_peck as long = " << UE_peck << " ;" << endl;
CS  << "   public const uint UE_bushel = " << hex <<"0x"<< UE_bushel << " ;" << endl;
Cpp << "#define UE_bushel " << hex <<"0x"<< UE_bushel <<  endl;
VB  << "public const UE_bushel as long = " << UE_bushel << " ;" << endl;
CS  << "   public const uint UE_quarter = " << hex <<"0x"<< UE_quarter << " ;" << endl;
Cpp << "#define UE_quarter " << hex <<"0x"<< UE_quarter <<  endl;
VB  << "public const UE_quarter as long = " << UE_quarter << " ;" << endl;
CS  << "   public const uint UE_tun = " << hex <<"0x"<< UE_tun << " ;" << endl;
Cpp << "#define UE_tun " << hex <<"0x"<< UE_tun <<  endl;
VB  << "public const UE_tun as long = " << UE_tun << " ;" << endl;
CS  << "   public const uint UE_chaldron = " << hex <<"0x"<< UE_chaldron << " ;" << endl;
Cpp << "#define UE_chaldron " << hex <<"0x"<< UE_chaldron <<  endl;
VB  << "public const UE_chaldron as long = " << UE_chaldron << " ;" << endl;
CS  << "   public const uint UE_fluid_minim_Imperial = " << hex <<"0x"<< UE_fluid_minim_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_minim_Imperial " << hex <<"0x"<< UE_fluid_minim_Imperial <<  endl;
VB  << "public const UE_fluid_minim_Imperial as long = " << UE_fluid_minim_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_drachm_Imperial = " << hex <<"0x"<< UE_fluid_drachm_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_drachm_Imperial " << hex <<"0x"<< UE_fluid_drachm_Imperial <<  endl;
VB  << "public const UE_fluid_drachm_Imperial as long = " << UE_fluid_drachm_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_ounce_Imperial = " << hex <<"0x"<< UE_fluid_ounce_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_ounce_Imperial " << hex <<"0x"<< UE_fluid_ounce_Imperial <<  endl;
VB  << "public const UE_fluid_ounce_Imperial as long = " << UE_fluid_ounce_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_gill_Imperial = " << hex <<"0x"<< UE_fluid_gill_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_gill_Imperial " << hex <<"0x"<< UE_fluid_gill_Imperial <<  endl;
VB  << "public const UE_fluid_gill_Imperial as long = " << UE_fluid_gill_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_mutchin_Imperial = " << hex <<"0x"<< UE_fluid_mutchin_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_mutchin_Imperial " << hex <<"0x"<< UE_fluid_mutchin_Imperial <<  endl;
VB  << "public const UE_fluid_mutchin_Imperial as long = " << UE_fluid_mutchin_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_pint_Imperial = " << hex <<"0x"<< UE_fluid_pint_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_pint_Imperial " << hex <<"0x"<< UE_fluid_pint_Imperial <<  endl;
VB  << "public const UE_fluid_pint_Imperial as long = " << UE_fluid_pint_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_fifth_Imperial = " << hex <<"0x"<< UE_fluid_fifth_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_fifth_Imperial " << hex <<"0x"<< UE_fluid_fifth_Imperial <<  endl;
VB  << "public const UE_fluid_fifth_Imperial as long = " << UE_fluid_fifth_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_quart_Imperial = " << hex <<"0x"<< UE_fluid_quart_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_quart_Imperial " << hex <<"0x"<< UE_fluid_quart_Imperial <<  endl;
VB  << "public const UE_fluid_quart_Imperial as long = " << UE_fluid_quart_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_gallon_Imperial = " << hex <<"0x"<< UE_fluid_gallon_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_gallon_Imperial " << hex <<"0x"<< UE_fluid_gallon_Imperial <<  endl;
VB  << "public const UE_fluid_gallon_Imperial as long = " << UE_fluid_gallon_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_peck_Imperial = " << hex <<"0x"<< UE_fluid_peck_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_peck_Imperial " << hex <<"0x"<< UE_fluid_peck_Imperial <<  endl;
VB  << "public const UE_fluid_peck_Imperial as long = " << UE_fluid_peck_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_bushel_Imperial = " << hex <<"0x"<< UE_fluid_bushel_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_bushel_Imperial " << hex <<"0x"<< UE_fluid_bushel_Imperial <<  endl;
VB  << "public const UE_fluid_bushel_Imperial as long = " << UE_fluid_bushel_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_quarter_Imperial = " << hex <<"0x"<< UE_fluid_quarter_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_quarter_Imperial " << hex <<"0x"<< UE_fluid_quarter_Imperial <<  endl;
VB  << "public const UE_fluid_quarter_Imperial as long = " << UE_fluid_quarter_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_tun_Imperial = " << hex <<"0x"<< UE_fluid_tun_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_tun_Imperial " << hex <<"0x"<< UE_fluid_tun_Imperial <<  endl;
VB  << "public const UE_fluid_tun_Imperial as long = " << UE_fluid_tun_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_chaldron_Imperial = " << hex <<"0x"<< UE_fluid_chaldron_Imperial << " ;" << endl;
Cpp << "#define UE_fluid_chaldron_Imperial " << hex <<"0x"<< UE_fluid_chaldron_Imperial <<  endl;
VB  << "public const UE_fluid_chaldron_Imperial as long = " << UE_fluid_chaldron_Imperial << " ;" << endl;
CS  << "   public const uint UE_fluid_minim_US = " << hex <<"0x"<< UE_fluid_minim_US << " ;" << endl;
Cpp << "#define UE_fluid_minim_US " << hex <<"0x"<< UE_fluid_minim_US <<  endl;
VB  << "public const UE_fluid_minim_US as long = " << UE_fluid_minim_US << " ;" << endl;
CS  << "   public const uint UE_fluid_drachm_US = " << hex <<"0x"<< UE_fluid_drachm_US << " ;" << endl;
Cpp << "#define UE_fluid_drachm_US " << hex <<"0x"<< UE_fluid_drachm_US <<  endl;
VB  << "public const UE_fluid_drachm_US as long = " << UE_fluid_drachm_US << " ;" << endl;
CS  << "   public const uint UE_fluid_ounce_US = " << hex <<"0x"<< UE_fluid_ounce_US << " ;" << endl;
Cpp << "#define UE_fluid_ounce_US " << hex <<"0x"<< UE_fluid_ounce_US <<  endl;
VB  << "public const UE_fluid_ounce_US as long = " << UE_fluid_ounce_US << " ;" << endl;
CS  << "   public const uint UE_fluid_pint_US = " << hex <<"0x"<< UE_fluid_pint_US << " ;" << endl;
Cpp << "#define UE_fluid_pint_US " << hex <<"0x"<< UE_fluid_pint_US <<  endl;
VB  << "public const UE_fluid_pint_US as long = " << UE_fluid_pint_US << " ;" << endl;
CS  << "   public const uint UE_fluid_gill_US = " << hex <<"0x"<< UE_fluid_gill_US << " ;" << endl;
Cpp << "#define UE_fluid_gill_US " << hex <<"0x"<< UE_fluid_gill_US <<  endl;
VB  << "public const UE_fluid_gill_US as long = " << UE_fluid_gill_US << " ;" << endl;
CS  << "   public const uint UE_fluid_fifth_US = " << hex <<"0x"<< UE_fluid_fifth_US << " ;" << endl;
Cpp << "#define UE_fluid_fifth_US " << hex <<"0x"<< UE_fluid_fifth_US <<  endl;
VB  << "public const UE_fluid_fifth_US as long = " << UE_fluid_fifth_US << " ;" << endl;
CS  << "   public const uint UE_fluid_quart_US = " << hex <<"0x"<< UE_fluid_quart_US << " ;" << endl;
Cpp << "#define UE_fluid_quart_US " << hex <<"0x"<< UE_fluid_quart_US <<  endl;
VB  << "public const UE_fluid_quart_US as long = " << UE_fluid_quart_US << " ;" << endl;
CS  << "   public const uint UE_fluid_gallon_US = " << hex <<"0x"<< UE_fluid_gallon_US << " ;" << endl;
Cpp << "#define UE_fluid_gallon_US " << hex <<"0x"<< UE_fluid_gallon_US <<  endl;
VB  << "public const UE_fluid_gallon_US as long = " << UE_fluid_gallon_US << " ;" << endl;
CS  << "   public const uint UE_dry_minim_Imperial = " << hex <<"0x"<< UE_dry_minim_Imperial << " ;" << endl;
Cpp << "#define UE_dry_minim_Imperial " << hex <<"0x"<< UE_dry_minim_Imperial <<  endl;
VB  << "public const UE_dry_minim_Imperial as long = " << UE_dry_minim_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_drachm_Imperial = " << hex <<"0x"<< UE_dry_drachm_Imperial << " ;" << endl;
Cpp << "#define UE_dry_drachm_Imperial " << hex <<"0x"<< UE_dry_drachm_Imperial <<  endl;
VB  << "public const UE_dry_drachm_Imperial as long = " << UE_dry_drachm_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_ounce_Imperial = " << hex <<"0x"<< UE_dry_ounce_Imperial << " ;" << endl;
Cpp << "#define UE_dry_ounce_Imperial " << hex <<"0x"<< UE_dry_ounce_Imperial <<  endl;
VB  << "public const UE_dry_ounce_Imperial as long = " << UE_dry_ounce_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_pint_Imperial = " << hex <<"0x"<< UE_dry_pint_Imperial << " ;" << endl;
Cpp << "#define UE_dry_pint_Imperial " << hex <<"0x"<< UE_dry_pint_Imperial <<  endl;
VB  << "public const UE_dry_pint_Imperial as long = " << UE_dry_pint_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_gill_Imperial = " << hex <<"0x"<< UE_dry_gill_Imperial << " ;" << endl;
Cpp << "#define UE_dry_gill_Imperial " << hex <<"0x"<< UE_dry_gill_Imperial <<  endl;
VB  << "public const UE_dry_gill_Imperial as long = " << UE_dry_gill_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_fifth_Imperial = " << hex <<"0x"<< UE_dry_fifth_Imperial << " ;" << endl;
Cpp << "#define UE_dry_fifth_Imperial " << hex <<"0x"<< UE_dry_fifth_Imperial <<  endl;
VB  << "public const UE_dry_fifth_Imperial as long = " << UE_dry_fifth_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_quart_Imperial = " << hex <<"0x"<< UE_dry_quart_Imperial << " ;" << endl;
Cpp << "#define UE_dry_quart_Imperial " << hex <<"0x"<< UE_dry_quart_Imperial <<  endl;
VB  << "public const UE_dry_quart_Imperial as long = " << UE_dry_quart_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_gallon_Imperial = " << hex <<"0x"<< UE_dry_gallon_Imperial << " ;" << endl;
Cpp << "#define UE_dry_gallon_Imperial " << hex <<"0x"<< UE_dry_gallon_Imperial <<  endl;
VB  << "public const UE_dry_gallon_Imperial as long = " << UE_dry_gallon_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_peck_Imperial = " << hex <<"0x"<< UE_dry_peck_Imperial << " ;" << endl;
Cpp << "#define UE_dry_peck_Imperial " << hex <<"0x"<< UE_dry_peck_Imperial <<  endl;
VB  << "public const UE_dry_peck_Imperial as long = " << UE_dry_peck_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_bushel_Imperial = " << hex <<"0x"<< UE_dry_bushel_Imperial << " ;" << endl;
Cpp << "#define UE_dry_bushel_Imperial " << hex <<"0x"<< UE_dry_bushel_Imperial <<  endl;
VB  << "public const UE_dry_bushel_Imperial as long = " << UE_dry_bushel_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_quarter_Imperial = " << hex <<"0x"<< UE_dry_quarter_Imperial << " ;" << endl;
Cpp << "#define UE_dry_quarter_Imperial " << hex <<"0x"<< UE_dry_quarter_Imperial <<  endl;
VB  << "public const UE_dry_quarter_Imperial as long = " << UE_dry_quarter_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_tun_Imperial = " << hex <<"0x"<< UE_dry_tun_Imperial << " ;" << endl;
Cpp << "#define UE_dry_tun_Imperial " << hex <<"0x"<< UE_dry_tun_Imperial <<  endl;
VB  << "public const UE_dry_tun_Imperial as long = " << UE_dry_tun_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_chaldron_Imperial = " << hex <<"0x"<< UE_dry_chaldron_Imperial << " ;" << endl;
Cpp << "#define UE_dry_chaldron_Imperial " << hex <<"0x"<< UE_dry_chaldron_Imperial <<  endl;
VB  << "public const UE_dry_chaldron_Imperial as long = " << UE_dry_chaldron_Imperial << " ;" << endl;
CS  << "   public const uint UE_dry_minimUS = " << hex <<"0x"<< UE_dry_minimUS << " ;" << endl;
Cpp << "#define UE_dry_minimUS " << hex <<"0x"<< UE_dry_minimUS <<  endl;
VB  << "public const UE_dry_minimUS as long = " << UE_dry_minimUS << " ;" << endl;
CS  << "   public const uint UE_dry_drachm_US = " << hex <<"0x"<< UE_dry_drachm_US << " ;" << endl;
Cpp << "#define UE_dry_drachm_US " << hex <<"0x"<< UE_dry_drachm_US <<  endl;
VB  << "public const UE_dry_drachm_US as long = " << UE_dry_drachm_US << " ;" << endl;
CS  << "   public const uint UE_dry_ounce_US = " << hex <<"0x"<< UE_dry_ounce_US << " ;" << endl;
Cpp << "#define UE_dry_ounce_US " << hex <<"0x"<< UE_dry_ounce_US <<  endl;
VB  << "public const UE_dry_ounce_US as long = " << UE_dry_ounce_US << " ;" << endl;
CS  << "   public const uint UE_dry_pint_US = " << hex <<"0x"<< UE_dry_pint_US << " ;" << endl;
Cpp << "#define UE_dry_pint_US " << hex <<"0x"<< UE_dry_pint_US <<  endl;
VB  << "public const UE_dry_pint_US as long = " << UE_dry_pint_US << " ;" << endl;
CS  << "   public const uint UE_dry_gill_US = " << hex <<"0x"<< UE_dry_gill_US << " ;" << endl;
Cpp << "#define UE_dry_gill_US " << hex <<"0x"<< UE_dry_gill_US <<  endl;
VB  << "public const UE_dry_gill_US as long = " << UE_dry_gill_US << " ;" << endl;
CS  << "   public const uint UE_dry_fifth_US = " << hex <<"0x"<< UE_dry_fifth_US << " ;" << endl;
Cpp << "#define UE_dry_fifth_US " << hex <<"0x"<< UE_dry_fifth_US <<  endl;
VB  << "public const UE_dry_fifth_US as long = " << UE_dry_fifth_US << " ;" << endl;
CS  << "   public const uint UE_dry_quart_US = " << hex <<"0x"<< UE_dry_quart_US << " ;" << endl;
Cpp << "#define UE_dry_quart_US " << hex <<"0x"<< UE_dry_quart_US <<  endl;
VB  << "public const UE_dry_quart_US as long = " << UE_dry_quart_US << " ;" << endl;
CS  << "   public const uint UE_dry_gallon_US = " << hex <<"0x"<< UE_dry_gallon_US << " ;" << endl;
Cpp << "#define UE_dry_gallon_US " << hex <<"0x"<< UE_dry_gallon_US <<  endl;
VB  << "public const UE_dry_gallon_US as long = " << UE_dry_gallon_US << " ;" << endl;
CS  << "   public const uint UE_dry_peck_US = " << hex <<"0x"<< UE_dry_peck_US << " ;" << endl;
Cpp << "#define UE_dry_peck_US " << hex <<"0x"<< UE_dry_peck_US <<  endl;
VB  << "public const UE_dry_peck_US as long = " << UE_dry_peck_US << " ;" << endl;
CS  << "   public const uint UE_dry_bushel_US = " << hex <<"0x"<< UE_dry_bushel_US << " ;" << endl;
Cpp << "#define UE_dry_bushel_US " << hex <<"0x"<< UE_dry_bushel_US <<  endl;
VB  << "public const UE_dry_bushel_US as long = " << UE_dry_bushel_US << " ;" << endl;
CS  << "   public const uint UE_dry_quarter_US = " << hex <<"0x"<< UE_dry_quarter_US << " ;" << endl;
Cpp << "#define UE_dry_quarter_US " << hex <<"0x"<< UE_dry_quarter_US <<  endl;
VB  << "public const UE_dry_quarter_US as long = " << UE_dry_quarter_US << " ;" << endl;
CS  << "   public const uint UE_dry_tun_US = " << hex <<"0x"<< UE_dry_tun_US << " ;" << endl;
Cpp << "#define UE_dry_tun_US " << hex <<"0x"<< UE_dry_tun_US <<  endl;
VB  << "public const UE_dry_tun_US as long = " << UE_dry_tun_US << " ;" << endl;
CS  << "   public const uint UE_dry_chaldron_US = " << hex <<"0x"<< UE_dry_chaldron_US << " ;" << endl;
Cpp << "#define UE_dry_chaldron_US " << hex <<"0x"<< UE_dry_chaldron_US <<  endl;
VB  << "public const UE_dry_chaldron_US as long = " << UE_dry_chaldron_US << " ;" << endl;
CS  << "   public const uint UC_radian_angle = " << hex <<"0x"<< UC_radian_angle << " ;" << endl;
Cpp << "#define UC_radian_angle " << hex <<"0x"<< UC_radian_angle <<  endl;
VB  << "public const UC_radian_angle as long = " << UC_radian_angle << " ;" << endl;
CS  << "   public const uint UC_degree_angle = " << hex <<"0x"<< UC_degree_angle << " ;" << endl;
Cpp << "#define UC_degree_angle " << hex <<"0x"<< UC_degree_angle <<  endl;
VB  << "public const UC_degree_angle as long = " << UC_degree_angle << " ;" << endl;
CS  << "   public const uint UC_degrees_longitude = " << hex <<"0x"<< UC_degrees_longitude << " ;" << endl;
Cpp << "#define UC_degrees_longitude " << hex <<"0x"<< UC_degrees_longitude <<  endl;
VB  << "public const UC_degrees_longitude as long = " << UC_degrees_longitude << " ;" << endl;
CS  << "   public const uint UC_degrees_latitutude = " << hex <<"0x"<< UC_degrees_latitutude << " ;" << endl;
Cpp << "#define UC_degrees_latitutude " << hex <<"0x"<< UC_degrees_latitutude <<  endl;
VB  << "public const UC_degrees_latitutude as long = " << UC_degrees_latitutude << " ;" << endl;
CS  << "   public const uint UC_degree_from_east = " << hex <<"0x"<< UC_degree_from_east << " ;" << endl;
Cpp << "#define UC_degree_from_east " << hex <<"0x"<< UC_degree_from_east <<  endl;
VB  << "public const UC_degree_from_east as long = " << UC_degree_from_east << " ;" << endl;
CS  << "   public const uint UC_degree_from_north = " << hex <<"0x"<< UC_degree_from_north << " ;" << endl;
Cpp << "#define UC_degree_from_north " << hex <<"0x"<< UC_degree_from_north <<  endl;
VB  << "public const UC_degree_from_north as long = " << UC_degree_from_north << " ;" << endl;
CS  << "   public const uint UC_gradian_angle = " << hex <<"0x"<< UC_gradian_angle << " ;" << endl;
Cpp << "#define UC_gradian_angle " << hex <<"0x"<< UC_gradian_angle <<  endl;
VB  << "public const UC_gradian_angle as long = " << UC_gradian_angle << " ;" << endl;
CS  << "   public const uint UC_gradian_angle = " << hex <<"0x"<< UC_gradian_angle << " ;" << endl;
Cpp << "#define UC_gradian_angle " << hex <<"0x"<< UC_gradian_angle <<  endl;
VB  << "public const UC_gradian_angle as long = " << UC_gradian_angle << " ;" << endl;
CS  << "   public const uint UC_gradian_angle = " << hex <<"0x"<< UC_gradian_angle << " ;" << endl;
Cpp << "#define UC_gradian_angle " << hex <<"0x"<< UC_gradian_angle <<  endl;
VB  << "public const UC_gradian_angle as long = " << UC_gradian_angle << " ;" << endl;
CS  << "   public const uint UC_steradian = " << hex <<"0x"<< UC_steradian << " ;" << endl;
Cpp << "#define UC_steradian " << hex <<"0x"<< UC_steradian <<  endl;
VB  << "public const UC_steradian as long = " << UC_steradian << " ;" << endl;
CS  << "   public const uint UC_hertz = " << hex <<"0x"<< UC_hertz << " ;" << endl;
Cpp << "#define UC_hertz " << hex <<"0x"<< UC_hertz <<  endl;
VB  << "public const UC_hertz as long = " << UC_hertz << " ;" << endl;
CS  << "   public const uint UC_fresnel = " << hex <<"0x"<< UC_fresnel << " ;" << endl;
Cpp << "#define UC_fresnel " << hex <<"0x"<< UC_fresnel <<  endl;
VB  << "public const UC_fresnel as long = " << UC_fresnel << " ;" << endl;
CS  << "   public const uint UC_W_per_m_K_thermal_conductivity = " << hex <<"0x"<< UC_W_per_m_K_thermal_conductivity << " ;" << endl;
Cpp << "#define UC_W_per_m_K_thermal_conductivity " << hex <<"0x"<< UC_W_per_m_K_thermal_conductivity <<  endl;
VB  << "public const UC_W_per_m_K_thermal_conductivity as long = " << UC_W_per_m_K_thermal_conductivity << " ;" << endl;
CS  << "   public const uint UC_joule_energy = " << hex <<"0x"<< UC_joule_energy << " ;" << endl;
Cpp << "#define UC_joule_energy " << hex <<"0x"<< UC_joule_energy <<  endl;
VB  << "public const UC_joule_energy as long = " << UC_joule_energy << " ;" << endl;
CS  << "   public const uint UC_kilo_joule_energy = " << hex <<"0x"<< UC_kilo_joule_energy << " ;" << endl;
Cpp << "#define UC_kilo_joule_energy " << hex <<"0x"<< UC_kilo_joule_energy <<  endl;
VB  << "public const UC_kilo_joule_energy as long = " << UC_kilo_joule_energy << " ;" << endl;
CS  << "   public const uint UC_mega_joule_energy = " << hex <<"0x"<< UC_mega_joule_energy << " ;" << endl;
Cpp << "#define UC_mega_joule_energy " << hex <<"0x"<< UC_mega_joule_energy <<  endl;
VB  << "public const UC_mega_joule_energy as long = " << UC_mega_joule_energy << " ;" << endl;
CS  << "   public const uint UE_calorie_energy = " << hex <<"0x"<< UE_calorie_energy << " ;" << endl;
Cpp << "#define UE_calorie_energy " << hex <<"0x"<< UE_calorie_energy <<  endl;
VB  << "public const UE_calorie_energy as long = " << UE_calorie_energy << " ;" << endl;
CS  << "   public const uint UE_mega_calorie_energy = " << hex <<"0x"<< UE_mega_calorie_energy << " ;" << endl;
Cpp << "#define UE_mega_calorie_energy " << hex <<"0x"<< UE_mega_calorie_energy <<  endl;
VB  << "public const UE_mega_calorie_energy as long = " << UE_mega_calorie_energy << " ;" << endl;
CS  << "   public const uint UC_ergs = " << hex <<"0x"<< UC_ergs << " ;" << endl;
Cpp << "#define UC_ergs " << hex <<"0x"<< UC_ergs <<  endl;
VB  << "public const UC_ergs as long = " << UC_ergs << " ;" << endl;
CS  << "   public const uint UC_joule_energy = " << hex <<"0x"<< UC_joule_energy << " ;" << endl;
Cpp << "#define UC_joule_energy " << hex <<"0x"<< UC_joule_energy <<  endl;
VB  << "public const UC_joule_energy as long = " << UC_joule_energy << " ;" << endl;
CS  << "   public const uint UC_watt_hour = " << hex <<"0x"<< UC_watt_hour << " ;" << endl;
Cpp << "#define UC_watt_hour " << hex <<"0x"<< UC_watt_hour <<  endl;
VB  << "public const UC_watt_hour as long = " << UC_watt_hour << " ;" << endl;
CS  << "   public const uint UC_watt_day = " << hex <<"0x"<< UC_watt_day << " ;" << endl;
Cpp << "#define UC_watt_day " << hex <<"0x"<< UC_watt_day <<  endl;
VB  << "public const UC_watt_day as long = " << UC_watt_day << " ;" << endl;
CS  << "   public const uint UC_newton_force = " << hex <<"0x"<< UC_newton_force << " ;" << endl;
Cpp << "#define UC_newton_force " << hex <<"0x"<< UC_newton_force <<  endl;
VB  << "public const UC_newton_force as long = " << UC_newton_force << " ;" << endl;
CS  << "   public const uint UC_newton = " << hex <<"0x"<< UC_newton << " ;" << endl;
Cpp << "#define UC_newton " << hex <<"0x"<< UC_newton <<  endl;
VB  << "public const UC_newton as long = " << UC_newton << " ;" << endl;
CS  << "   public const uint UE_poundal = " << hex <<"0x"<< UE_poundal << " ;" << endl;
Cpp << "#define UE_poundal " << hex <<"0x"<< UE_poundal <<  endl;
VB  << "public const UE_poundal as long = " << UE_poundal << " ;" << endl;
CS  << "   public const uint UC_watt_radiant_flux = " << hex <<"0x"<< UC_watt_radiant_flux << " ;" << endl;
Cpp << "#define UC_watt_radiant_flux " << hex <<"0x"<< UC_watt_radiant_flux <<  endl;
VB  << "public const UC_watt_radiant_flux as long = " << UC_watt_radiant_flux << " ;" << endl;
CS  << "   public const uint UC_pascal_pressure = " << hex <<"0x"<< UC_pascal_pressure << " ;" << endl;
Cpp << "#define UC_pascal_pressure " << hex <<"0x"<< UC_pascal_pressure <<  endl;
VB  << "public const UC_pascal_pressure as long = " << UC_pascal_pressure << " ;" << endl;
CS  << "   public const uint UC_kPa = " << hex <<"0x"<< UC_kPa << " ;" << endl;
Cpp << "#define UC_kPa " << hex <<"0x"<< UC_kPa <<  endl;
VB  << "public const UC_kPa as long = " << UC_kPa << " ;" << endl;
CS  << "   public const uint UC_barye = " << hex <<"0x"<< UC_barye << " ;" << endl;
Cpp << "#define UC_barye " << hex <<"0x"<< UC_barye <<  endl;
VB  << "public const UC_barye as long = " << UC_barye << " ;" << endl;
CS  << "   public const uint UC_osmol = " << hex <<"0x"<< UC_osmol << " ;" << endl;
Cpp << "#define UC_osmol " << hex <<"0x"<< UC_osmol <<  endl;
VB  << "public const UC_osmol as long = " << UC_osmol << " ;" << endl;
CS  << "   public const uint UC_pascal_second_dynamic_viscosity = " << hex <<"0x"<< UC_pascal_second_dynamic_viscosity << " ;" << endl;
Cpp << "#define UC_pascal_second_dynamic_viscosity " << hex <<"0x"<< UC_pascal_second_dynamic_viscosity <<  endl;
VB  << "public const UC_pascal_second_dynamic_viscosity as long = " << UC_pascal_second_dynamic_viscosity << " ;" << endl;
CS  << "   public const uint UC_poise = " << hex <<"0x"<< UC_poise << " ;" << endl;
Cpp << "#define UC_poise " << hex <<"0x"<< UC_poise <<  endl;
VB  << "public const UC_poise as long = " << UC_poise << " ;" << endl;
CS  << "   public const uint UC_m2_per_sec_kinematic_viscosity = " << hex <<"0x"<< UC_m2_per_sec_kinematic_viscosity << " ;" << endl;
Cpp << "#define UC_m2_per_sec_kinematic_viscosity " << hex <<"0x"<< UC_m2_per_sec_kinematic_viscosity <<  endl;
VB  << "public const UC_m2_per_sec_kinematic_viscosity as long = " << UC_m2_per_sec_kinematic_viscosity << " ;" << endl;
CS  << "   public const uint UC_stock = " << hex <<"0x"<< UC_stock << " ;" << endl;
Cpp << "#define UC_stock " << hex <<"0x"<< UC_stock <<  endl;
VB  << "public const UC_stock as long = " << UC_stock << " ;" << endl;
CS  << "   public const uint UC_ampere_current = " << hex <<"0x"<< UC_ampere_current << " ;" << endl;
Cpp << "#define UC_ampere_current " << hex <<"0x"<< UC_ampere_current <<  endl;
VB  << "public const UC_ampere_current as long = " << UC_ampere_current << " ;" << endl;
CS  << "   public const uint UC_biot = " << hex <<"0x"<< UC_biot << " ;" << endl;
Cpp << "#define UC_biot " << hex <<"0x"<< UC_biot <<  endl;
VB  << "public const UC_biot as long = " << UC_biot << " ;" << endl;
CS  << "   public const uint UC_faraday_charge = " << hex <<"0x"<< UC_faraday_charge << " ;" << endl;
Cpp << "#define UC_faraday_charge " << hex <<"0x"<< UC_faraday_charge <<  endl;
VB  << "public const UC_faraday_charge as long = " << UC_faraday_charge << " ;" << endl;
CS  << "   public const uint UC_volt_electric_potential = " << hex <<"0x"<< UC_volt_electric_potential << " ;" << endl;
Cpp << "#define UC_volt_electric_potential " << hex <<"0x"<< UC_volt_electric_potential <<  endl;
VB  << "public const UC_volt_electric_potential as long = " << UC_volt_electric_potential << " ;" << endl;
CS  << "   public const uint UC_volt = " << hex <<"0x"<< UC_volt << " ;" << endl;
Cpp << "#define UC_volt " << hex <<"0x"<< UC_volt <<  endl;
VB  << "public const UC_volt as long = " << UC_volt << " ;" << endl;
CS  << "   public const uint UC_volt_electromotive_force_D = " << hex <<"0x"<< UC_volt_electromotive_force_D << " ;" << endl;
Cpp << "#define UC_volt_electromotive_force_D " << hex <<"0x"<< UC_volt_electromotive_force_D <<  endl;
VB  << "public const UC_volt_electromotive_force_D as long = " << UC_volt_electromotive_force_D << " ;" << endl;
CS  << "   public const uint UC_farad = " << hex <<"0x"<< UC_farad << " ;" << endl;
Cpp << "#define UC_farad " << hex <<"0x"<< UC_farad <<  endl;
VB  << "public const UC_farad as long = " << UC_farad << " ;" << endl;
CS  << "   public const uint UC_ohm = " << hex <<"0x"<< UC_ohm << " ;" << endl;
Cpp << "#define UC_ohm " << hex <<"0x"<< UC_ohm <<  endl;
VB  << "public const UC_ohm as long = " << UC_ohm << " ;" << endl;
CS  << "   public const uint UC_siemens = " << hex <<"0x"<< UC_siemens << " ;" << endl;
Cpp << "#define UC_siemens " << hex <<"0x"<< UC_siemens <<  endl;
VB  << "public const UC_siemens as long = " << UC_siemens << " ;" << endl;
CS  << "   public const uint UC_decisiemens = " << hex <<"0x"<< UC_decisiemens << " ;" << endl;
Cpp << "#define UC_decisiemens " << hex <<"0x"<< UC_decisiemens <<  endl;
VB  << "public const UC_decisiemens as long = " << UC_decisiemens << " ;" << endl;
CS  << "   public const uint UC_mho = " << hex <<"0x"<< UC_mho << " ;" << endl;
Cpp << "#define UC_mho " << hex <<"0x"<< UC_mho <<  endl;
VB  << "public const UC_mho as long = " << UC_mho << " ;" << endl;
CS  << "   public const uint UC_henry = " << hex <<"0x"<< UC_henry << " ;" << endl;
Cpp << "#define UC_henry " << hex <<"0x"<< UC_henry <<  endl;
VB  << "public const UC_henry as long = " << UC_henry << " ;" << endl;
CS  << "   public const uint UC_maxwell = " << hex <<"0x"<< UC_maxwell << " ;" << endl;
Cpp << "#define UC_maxwell " << hex <<"0x"<< UC_maxwell <<  endl;
VB  << "public const UC_maxwell as long = " << UC_maxwell << " ;" << endl;
CS  << "   public const uint UC_maxwell = " << hex <<"0x"<< UC_maxwell << " ;" << endl;
Cpp << "#define UC_maxwell " << hex <<"0x"<< UC_maxwell <<  endl;
VB  << "public const UC_maxwell as long = " << UC_maxwell << " ;" << endl;
CS  << "   public const uint UC_weber = " << hex <<"0x"<< UC_weber << " ;" << endl;
Cpp << "#define UC_weber " << hex <<"0x"<< UC_weber <<  endl;
VB  << "public const UC_weber as long = " << UC_weber << " ;" << endl;
CS  << "   public const uint UC_tesla = " << hex <<"0x"<< UC_tesla << " ;" << endl;
Cpp << "#define UC_tesla " << hex <<"0x"<< UC_tesla <<  endl;
VB  << "public const UC_tesla as long = " << UC_tesla << " ;" << endl;
CS  << "   public const uint UC_gauss = " << hex <<"0x"<< UC_gauss << " ;" << endl;
Cpp << "#define UC_gauss " << hex <<"0x"<< UC_gauss <<  endl;
VB  << "public const UC_gauss as long = " << UC_gauss << " ;" << endl;
CS  << "   public const uint UC_gamma = " << hex <<"0x"<< UC_gamma << " ;" << endl;
Cpp << "#define UC_gamma " << hex <<"0x"<< UC_gamma <<  endl;
VB  << "public const UC_gamma as long = " << UC_gamma << " ;" << endl;
CS  << "   public const uint UC_becquerel = " << hex <<"0x"<< UC_becquerel << " ;" << endl;
Cpp << "#define UC_becquerel " << hex <<"0x"<< UC_becquerel <<  endl;
VB  << "public const UC_becquerel as long = " << UC_becquerel << " ;" << endl;
CS  << "   public const uint UC_gray = " << hex <<"0x"<< UC_gray << " ;" << endl;
Cpp << "#define UC_gray " << hex <<"0x"<< UC_gray <<  endl;
VB  << "public const UC_gray as long = " << UC_gray << " ;" << endl;
CS  << "   public const uint UC_sievert = " << hex <<"0x"<< UC_sievert << " ;" << endl;
Cpp << "#define UC_sievert " << hex <<"0x"<< UC_sievert <<  endl;
VB  << "public const UC_sievert as long = " << UC_sievert << " ;" << endl;
CS  << "   public const uint UC_cm_per_second = " << hex <<"0x"<< UC_cm_per_second << " ;" << endl;
Cpp << "#define UC_cm_per_second " << hex <<"0x"<< UC_cm_per_second <<  endl;
VB  << "public const UC_cm_per_second as long = " << UC_cm_per_second << " ;" << endl;
CS  << "   public const uint UC_meters_per_second = " << hex <<"0x"<< UC_meters_per_second << " ;" << endl;
Cpp << "#define UC_meters_per_second " << hex <<"0x"<< UC_meters_per_second <<  endl;
VB  << "public const UC_meters_per_second as long = " << UC_meters_per_second << " ;" << endl;
CS  << "   public const uint UC_meters_per_day = " << hex <<"0x"<< UC_meters_per_day << " ;" << endl;
Cpp << "#define UC_meters_per_day " << hex <<"0x"<< UC_meters_per_day <<  endl;
VB  << "public const UC_meters_per_day as long = " << UC_meters_per_day << " ;" << endl;
CS  << "   public const uint UC_mm_per_day = " << hex <<"0x"<< UC_mm_per_day << " ;" << endl;
Cpp << "#define UC_mm_per_day " << hex <<"0x"<< UC_mm_per_day <<  endl;
VB  << "public const UC_mm_per_day as long = " << UC_mm_per_day << " ;" << endl;
CS  << "   public const uint UC_kilometers_per_day = " << hex <<"0x"<< UC_kilometers_per_day << " ;" << endl;
Cpp << "#define UC_kilometers_per_day " << hex <<"0x"<< UC_kilometers_per_day <<  endl;
VB  << "public const UC_kilometers_per_day as long = " << UC_kilometers_per_day << " ;" << endl;
CS  << "   public const uint UC_kilometers_per_hour = " << hex <<"0x"<< UC_kilometers_per_hour << " ;" << endl;
Cpp << "#define UC_kilometers_per_hour " << hex <<"0x"<< UC_kilometers_per_hour <<  endl;
VB  << "public const UC_kilometers_per_hour as long = " << UC_kilometers_per_hour << " ;" << endl;
CS  << "   public const uint UE_miles_per_hour = " << hex <<"0x"<< UE_miles_per_hour << " ;" << endl;
Cpp << "#define UE_miles_per_hour " << hex <<"0x"<< UE_miles_per_hour <<  endl;
VB  << "public const UE_miles_per_hour as long = " << UE_miles_per_hour << " ;" << endl;
CS  << "   public const uint UE_miles_per_day = " << hex <<"0x"<< UE_miles_per_day << " ;" << endl;
Cpp << "#define UE_miles_per_day " << hex <<"0x"<< UE_miles_per_day <<  endl;
VB  << "public const UE_miles_per_day as long = " << UE_miles_per_day << " ;" << endl;
CS  << "   public const uint UE_knots = " << hex <<"0x"<< UE_knots << " ;" << endl;
Cpp << "#define UE_knots " << hex <<"0x"<< UE_knots <<  endl;
VB  << "public const UE_knots as long = " << UE_knots << " ;" << endl;
CS  << "   public const uint UC_m2_kg = " << hex <<"0x"<< UC_m2_kg << " ;" << endl;
Cpp << "#define UC_m2_kg " << hex <<"0x"<< UC_m2_kg <<  endl;
VB  << "public const UC_m2_kg as long = " << UC_m2_kg << " ;" << endl;
CS  << "   public const uint UC_parts_per_hundred = " << hex <<"0x"<< UC_parts_per_hundred << " ;" << endl;
Cpp << "#define UC_parts_per_hundred " << hex <<"0x"<< UC_parts_per_hundred <<  endl;
VB  << "public const UC_parts_per_hundred as long = " << UC_parts_per_hundred << " ;" << endl;
CS  << "   public const uint UC_parts_per_thousand = " << hex <<"0x"<< UC_parts_per_thousand << " ;" << endl;
Cpp << "#define UC_parts_per_thousand " << hex <<"0x"<< UC_parts_per_thousand <<  endl;
VB  << "public const UC_parts_per_thousand as long = " << UC_parts_per_thousand << " ;" << endl;
CS  << "   public const uint UC_parts_per_million = " << hex <<"0x"<< UC_parts_per_million << " ;" << endl;
Cpp << "#define UC_parts_per_million " << hex <<"0x"<< UC_parts_per_million <<  endl;
VB  << "public const UC_parts_per_million as long = " << UC_parts_per_million << " ;" << endl;
CS  << "   public const uint UC_parts_per_billion = " << hex <<"0x"<< UC_parts_per_billion << " ;" << endl;
Cpp << "#define UC_parts_per_billion " << hex <<"0x"<< UC_parts_per_billion <<  endl;
VB  << "public const UC_parts_per_billion as long = " << UC_parts_per_billion << " ;" << endl;
CS  << "   public const uint UC_parts_per_trillion = " << hex <<"0x"<< UC_parts_per_trillion << " ;" << endl;
Cpp << "#define UC_parts_per_trillion " << hex <<"0x"<< UC_parts_per_trillion <<  endl;
VB  << "public const UC_parts_per_trillion as long = " << UC_parts_per_trillion << " ;" << endl;
CS  << "   public const uint UC_MJ_m2 = " << hex <<"0x"<< UC_MJ_m2 << " ;" << endl;
Cpp << "#define UC_MJ_m2 " << hex <<"0x"<< UC_MJ_m2 <<  endl;
VB  << "public const UC_MJ_m2 as long = " << UC_MJ_m2 << " ;" << endl;
CS  << "   public const uint UC_MJ_m2 = " << hex <<"0x"<< UC_MJ_m2 << " ;" << endl;
Cpp << "#define UC_MJ_m2 " << hex <<"0x"<< UC_MJ_m2 <<  endl;
VB  << "public const UC_MJ_m2 as long = " << UC_MJ_m2 << " ;" << endl;
CS  << "   public const uint UC_kg_MJ = " << hex <<"0x"<< UC_kg_MJ << " ;" << endl;
Cpp << "#define UC_kg_MJ " << hex <<"0x"<< UC_kg_MJ <<  endl;
VB  << "public const UC_kg_MJ as long = " << UC_kg_MJ << " ;" << endl;
CS  << "   public const uint UC_g_MJ = " << hex <<"0x"<< UC_g_MJ << " ;" << endl;
Cpp << "#define UC_g_MJ " << hex <<"0x"<< UC_g_MJ <<  endl;
VB  << "public const UC_g_MJ as long = " << UC_g_MJ << " ;" << endl;
CS  << "   public const uint UC_kJ_mole = " << hex <<"0x"<< UC_kJ_mole << " ;" << endl;
Cpp << "#define UC_kJ_mole " << hex <<"0x"<< UC_kJ_mole <<  endl;
VB  << "public const UC_kJ_mole as long = " << UC_kJ_mole << " ;" << endl;
CS  << "   public const uint UC_watt_day_m2 = " << hex <<"0x"<< UC_watt_day_m2 << " ;" << endl;
Cpp << "#define UC_watt_day_m2 " << hex <<"0x"<< UC_watt_day_m2 <<  endl;
VB  << "public const UC_watt_day_m2 as long = " << UC_watt_day_m2 << " ;" << endl;
CS  << "   public const uint UE_Langley = " << hex <<"0x"<< UE_Langley << " ;" << endl;
Cpp << "#define UE_Langley " << hex <<"0x"<< UE_Langley <<  endl;
VB  << "public const UE_Langley as long = " << UE_Langley << " ;" << endl;
CS  << "   public const uint UC_kg_kg = " << hex <<"0x"<< UC_kg_kg << " ;" << endl;
Cpp << "#define UC_kg_kg " << hex <<"0x"<< UC_kg_kg <<  endl;
VB  << "public const UC_kg_kg as long = " << UC_kg_kg << " ;" << endl;
CS  << "   public const uint UC_kg_ha = " << hex <<"0x"<< UC_kg_ha << " ;" << endl;
Cpp << "#define UC_kg_ha " << hex <<"0x"<< UC_kg_ha <<  endl;
VB  << "public const UC_kg_ha as long = " << UC_kg_ha << " ;" << endl;
CS  << "   public const uint UC_kg_m2 = " << hex <<"0x"<< UC_kg_m2 << " ;" << endl;
Cpp << "#define UC_kg_m2 " << hex <<"0x"<< UC_kg_m2 <<  endl;
VB  << "public const UC_kg_m2 as long = " << UC_kg_m2 << " ;" << endl;
CS  << "   public const uint UC_kg_m3 = " << hex <<"0x"<< UC_kg_m3 << " ;" << endl;
Cpp << "#define UC_kg_m3 " << hex <<"0x"<< UC_kg_m3 <<  endl;
VB  << "public const UC_kg_m3 as long = " << UC_kg_m3 << " ;" << endl;
CS  << "   public const uint UC_ml_g = " << hex <<"0x"<< UC_ml_g << " ;" << endl;
Cpp << "#define UC_ml_g " << hex <<"0x"<< UC_ml_g <<  endl;
VB  << "public const UC_ml_g as long = " << UC_ml_g << " ;" << endl;
CS  << "   public const uint UC_m3_m3 = " << hex <<"0x"<< UC_m3_m3 << " ;" << endl;
Cpp << "#define UC_m3_m3 " << hex <<"0x"<< UC_m3_m3 <<  endl;
VB  << "public const UC_m3_m3 as long = " << UC_m3_m3 << " ;" << endl;
CS  << "   public const uint UC_kg_solid_kg_liquid = " << hex <<"0x"<< UC_kg_solid_kg_liquid << " ;" << endl;
Cpp << "#define UC_kg_solid_kg_liquid " << hex <<"0x"<< UC_kg_solid_kg_liquid <<  endl;
VB  << "public const UC_kg_solid_kg_liquid as long = " << UC_kg_solid_kg_liquid << " ;" << endl;
CS  << "   public const uint UC_kg_kg = " << hex <<"0x"<< UC_kg_kg << " ;" << endl;
Cpp << "#define UC_kg_kg " << hex <<"0x"<< UC_kg_kg <<  endl;
VB  << "public const UC_kg_kg as long = " << UC_kg_kg << " ;" << endl;
CS  << "   public const uint UC_J_kg = " << hex <<"0x"<< UC_J_kg << " ;" << endl;
Cpp << "#define UC_J_kg " << hex <<"0x"<< UC_J_kg <<  endl;
VB  << "public const UC_J_kg as long = " << UC_J_kg << " ;" << endl;
CS  << "   public const uint UC_mEq_100g = " << hex <<"0x"<< UC_mEq_100g << " ;" << endl;
Cpp << "#define UC_mEq_100g " << hex <<"0x"<< UC_mEq_100g <<  endl;
VB  << "public const UC_mEq_100g as long = " << UC_mEq_100g << " ;" << endl;
CS  << "   public const uint UE_gallon_per_minute = " << hex <<"0x"<< UE_gallon_per_minute << " ;" << endl;
Cpp << "#define UE_gallon_per_minute " << hex <<"0x"<< UE_gallon_per_minute <<  endl;
VB  << "public const UE_gallon_per_minute as long = " << UE_gallon_per_minute << " ;" << endl;
CS  << "   public const uint UE_gallon_per_hour = " << hex <<"0x"<< UE_gallon_per_hour << " ;" << endl;
Cpp << "#define UE_gallon_per_hour " << hex <<"0x"<< UE_gallon_per_hour <<  endl;
VB  << "public const UE_gallon_per_hour as long = " << UE_gallon_per_hour << " ;" << endl;
CS  << "   public const uint UC_liter_per_minute = " << hex <<"0x"<< UC_liter_per_minute << " ;" << endl;
Cpp << "#define UC_liter_per_minute " << hex <<"0x"<< UC_liter_per_minute <<  endl;
VB  << "public const UC_liter_per_minute as long = " << UC_liter_per_minute << " ;" << endl;
CS  << "   public const uint UC_liter_per_hour = " << hex <<"0x"<< UC_liter_per_hour << " ;" << endl;
Cpp << "#define UC_liter_per_hour " << hex <<"0x"<< UC_liter_per_hour <<  endl;
VB  << "public const UC_liter_per_hour as long = " << UC_liter_per_hour << " ;" << endl;
CS  << "   public const uint UC_kg_per_day = " << hex <<"0x"<< UC_kg_per_day << " ;" << endl;
Cpp << "#define UC_kg_per_day " << hex <<"0x"<< UC_kg_per_day <<  endl;
VB  << "public const UC_kg_per_day as long = " << UC_kg_per_day << " ;" << endl;
CS  << "   public const uint UC_m3_per_minute = " << hex <<"0x"<< UC_m3_per_minute << " ;" << endl;
Cpp << "#define UC_m3_per_minute " << hex <<"0x"<< UC_m3_per_minute <<  endl;
VB  << "public const UC_m3_per_minute as long = " << UC_m3_per_minute << " ;" << endl;
CS  << "   public const uint UC_m3_per_hour = " << hex <<"0x"<< UC_m3_per_hour << " ;" << endl;
Cpp << "#define UC_m3_per_hour " << hex <<"0x"<< UC_m3_per_hour <<  endl;
VB  << "public const UC_m3_per_hour as long = " << UC_m3_per_hour << " ;" << endl;
CS  << "   public const uint UC_count_per_day = " << hex <<"0x"<< UC_count_per_day << " ;" << endl;
Cpp << "#define UC_count_per_day " << hex <<"0x"<< UC_count_per_day <<  endl;
VB  << "public const UC_count_per_day as long = " << UC_count_per_day << " ;" << endl;
CS  << "   public const uint UC_dS_m = " << hex <<"0x"<< UC_dS_m << " ;" << endl;
Cpp << "#define UC_dS_m " << hex <<"0x"<< UC_dS_m <<  endl;
VB  << "public const UC_dS_m as long = " << UC_dS_m << " ;" << endl;
CS  << "   public const uint UC_coulumb = " << hex <<"0x"<< UC_coulumb << " ;" << endl;
Cpp << "#define UC_coulumb " << hex <<"0x"<< UC_coulumb <<  endl;
VB  << "public const UC_coulumb as long = " << UC_coulumb << " ;" << endl;
CS  << "   public const uint UC_planck = " << hex <<"0x"<< UC_planck << " ;" << endl;
Cpp << "#define UC_planck " << hex <<"0x"<< UC_planck <<  endl;
VB  << "public const UC_planck as long = " << UC_planck << " ;" << endl;
CS  << "   public const uint UC_luminance_c_m2 = " << hex <<"0x"<< UC_luminance_c_m2 << " ;" << endl;
Cpp << "#define UC_luminance_c_m2 " << hex <<"0x"<< UC_luminance_c_m2 <<  endl;
VB  << "public const UC_luminance_c_m2 as long = " << UC_luminance_c_m2 << " ;" << endl;
CS  << "   public const uint UC_lambert = " << hex <<"0x"<< UC_lambert << " ;" << endl;
Cpp << "#define UC_lambert " << hex <<"0x"<< UC_lambert <<  endl;
VB  << "public const UC_lambert as long = " << UC_lambert << " ;" << endl;
CS  << "   public const uint UC_meter_lambert = " << hex <<"0x"<< UC_meter_lambert << " ;" << endl;
Cpp << "#define UC_meter_lambert " << hex <<"0x"<< UC_meter_lambert <<  endl;
VB  << "public const UC_meter_lambert as long = " << UC_meter_lambert << " ;" << endl;
CS  << "   public const uint UC_meter_lambert = " << hex <<"0x"<< UC_meter_lambert << " ;" << endl;
Cpp << "#define UC_meter_lambert " << hex <<"0x"<< UC_meter_lambert <<  endl;
VB  << "public const UC_meter_lambert as long = " << UC_meter_lambert << " ;" << endl;
CS  << "   public const uint UC_J_per_K_entropy = " << hex <<"0x"<< UC_J_per_K_entropy << " ;" << endl;
Cpp << "#define UC_J_per_K_entropy " << hex <<"0x"<< UC_J_per_K_entropy <<  endl;
VB  << "public const UC_J_per_K_entropy as long = " << UC_J_per_K_entropy << " ;" << endl;
CS  << "   public const uint UE_clausius = " << hex <<"0x"<< UE_clausius << " ;" << endl;
Cpp << "#define UE_clausius " << hex <<"0x"<< UE_clausius <<  endl;
VB  << "public const UE_clausius as long = " << UE_clausius << " ;" << endl;
CS  << "   public const uint UC_watt_power = " << hex <<"0x"<< UC_watt_power << " ;" << endl;
Cpp << "#define UC_watt_power " << hex <<"0x"<< UC_watt_power <<  endl;
VB  << "public const UC_watt_power as long = " << UC_watt_power << " ;" << endl;
CS  << "   public const uint UC_W_steradian_radient_intensity = " << hex <<"0x"<< UC_W_steradian_radient_intensity << " ;" << endl;
Cpp << "#define UC_W_steradian_radient_intensity " << hex <<"0x"<< UC_W_steradian_radient_intensity <<  endl;
VB  << "public const UC_W_steradian_radient_intensity as long = " << UC_W_steradian_radient_intensity << " ;" << endl;
CS  << "   public const uint UC_oersted = " << hex <<"0x"<< UC_oersted << " ;" << endl;
Cpp << "#define UC_oersted " << hex <<"0x"<< UC_oersted <<  endl;
VB  << "public const UC_oersted as long = " << UC_oersted << " ;" << endl;
CS  << "   public const uint UC_volt_per_meter = " << hex <<"0x"<< UC_volt_per_meter << " ;" << endl;
Cpp << "#define UC_volt_per_meter " << hex <<"0x"<< UC_volt_per_meter <<  endl;
VB  << "public const UC_volt_per_meter as long = " << UC_volt_per_meter << " ;" << endl;
CS  << "   public const uint UT_second = " << hex <<"0x"<< UT_second << " ;" << endl;
Cpp << "#define UT_second " << hex <<"0x"<< UT_second <<  endl;
VB  << "public const UT_second as long = " << UT_second << " ;" << endl;
CS  << "}" << endl;
Cpp  << "#endif" << endl;
};
