#include "C:\dev\common\measure\units.h"
#define CLEAN_UC_unitless UC_unitless
#define CLEAN_UC_code UC_code
#define CLEAN_UC_unit UC_unit
#define CLEAN_UC_count UC_count
#define CLEAN_UC_percent UC_percent
#define CLEAN_UC_decimal_percent UC_decimal_percent
#define CLEAN_UC_index UC_index
#define CLEAN_UC_adjustment UC_adjustment
#define CLEAN_UC_ratio UC_ratio
#define CLEAN_UC_fraction UC_fraction
#define CLEAN_UC_probability UC_probability
#define CLEAN_UC_pH UC_pH
#define CLEAN_UT_time UT_time
#define CLEAN_UT_date UT_date
#define CLEAN_UT_day_of_year UT_day_of_year
#define CLEAN_UT_sunday UT_sunday
#define CLEAN_UT_monday UT_monday
#define CLEAN_UT_tuesday UT_tuesday
#define CLEAN_UT_wednesday UT_wednesday
#define CLEAN_UT_thursday UT_thursday
#define CLEAN_UT_friday UT_friday
#define CLEAN_UT_saturday UT_saturday
#define CLEAN_UT_day_of_month UT_day_of_month
#define CLEAN_UT_day_of_month_1 UT_day_of_month_1
#define CLEAN_UT_day_of_month_31 UT_day_of_month_31
#define CLEAN_UT_week UT_week
#define CLEAN_UT_fortnight UT_fortnight
#define CLEAN_UT_month UT_month
#define CLEAN_UT_january UT_january
#define CLEAN_UT_february UT_february
#define CLEAN_UT_march UT_march
#define CLEAN_UT_april UT_april
#define CLEAN_UT_may UT_may
#define CLEAN_UT_june UT_june
#define CLEAN_UT_july UT_july
#define CLEAN_UT_august UT_august
#define CLEAN_UT_september UT_september
#define CLEAN_UT_october UT_october
#define CLEAN_UT_november UT_november
#define CLEAN_UT_december UT_december
#define CLEAN_UT_quarter UT_quarter
#define CLEAN_UT_quarter_1 UT_quarter_1
#define CLEAN_UT_quarter_2 UT_quarter_2
#define CLEAN_UT_quarter_3 UT_quarter_3
#define CLEAN_UT_quarter_4 UT_quarter_4
#define CLEAN_UT_trimester UT_trimester
#define CLEAN_UT_trimester_1 UT_trimester_1
#define CLEAN_UT_trimester_2 UT_trimester_2
#define CLEAN_UT_trimester_3 UT_trimester_3
#define CLEAN_UT_biannum UT_biannum
#define CLEAN_UT_biannum_1 UT_biannum_1
#define CLEAN_UT_biannum_2 UT_biannum_2
#define CLEAN_UT_0_seconds UT_0_seconds
#define CLEAN_UT_1_second UT_1_second
#define CLEAN_UT_30_seconds UT_30_seconds
#define CLEAN_UT_60_seconds UT_60_seconds
#define CLEAN_UT_0_minutes UT_0_minutes
#define CLEAN_UT_1_minute UT_1_minute
#define CLEAN_UT_10_minutes UT_10_minutes
#define CLEAN_UT_15_minutes UT_15_minutes
#define CLEAN_UT_30_minutes UT_30_minutes
#define CLEAN_UT_half_hour UT_half_hour
#define CLEAN_UT_60_minutes UT_60_minutes
#define CLEAN_UT_0_hours UT_0_hours
#define CLEAN_UT_1_hour UT_1_hour
#define CLEAN_UT_24_hours UT_24_hours
#define CLEAN_UT_second UT_second
#define CLEAN_UT_millisecond UT_millisecond
#define CLEAN_UT_minute UT_minute
#define CLEAN_UT_hour UT_hour
#define CLEAN_UT_day UT_day
#define CLEAN_UT_year UT_year
#define CLEAN_UT_decade UT_decade
#define CLEAN_UT_century UT_century
#define CLEAN_UT_millenium UT_millenium
#define CLEAN_UC_celcius UC_celcius
#define CLEAN_UE_Farenheit UE_Farenheit
#define CLEAN_UC_kelvin UC_kelvin
#define CLEAN_UE_Rankine UE_Rankine
#define CLEAN_UC_celcius_degree_days UC_celcius_degree_days
#define CLEAN_UE_Farenheit_degree_days UE_Farenheit_degree_days
#define CLEAN_UC_Equivelent_weight UC_Equivelent_weight
#define CLEAN_UC_mEq UC_mEq
#define CLEAN_UC_mole UC_mole
#define CLEAN_UC_nanogram_mass UC_nanogram_mass
#define CLEAN_UC_microgram_mass UC_microgram_mass
#define CLEAN_UC_mg_mass UC_mg_mass
#define CLEAN_UC_cg_mass UC_cg_mass
#define CLEAN_UC_dg_mass UC_dg_mass
#define CLEAN_UC_gram_mass UC_gram_mass
#define CLEAN_UC_g UC_g
#define CLEAN_UC_Dg_mass UC_Dg_mass
#define CLEAN_UC_hg_mass UC_hg_mass
#define CLEAN_UC_kg_mass UC_kg_mass
#define CLEAN_UC_tonne_mass UC_tonne_mass
#define CLEAN_UE_grain UE_grain
#define CLEAN_UE_avoirdupois_dram UE_avoirdupois_dram
#define CLEAN_UE_avoirdupois_ounce UE_avoirdupois_ounce
#define CLEAN_UE_avoiddupois_pound UE_avoiddupois_pound
#define CLEAN_UE_avoirdupois_pound UE_avoirdupois_pound
#define CLEAN_UE_avoirdupois_clove UE_avoirdupois_clove
#define CLEAN_UE_avoirdupois_butchers_stone UE_avoirdupois_butchers_stone
#define CLEAN_UE_avoirdupois_stone UE_avoirdupois_stone
#define CLEAN_UE_avoirdupois_tod UE_avoirdupois_tod
#define CLEAN_UE_avoirdupois_quarter UE_avoirdupois_quarter
#define CLEAN_UE_avoirdupois_hundredweight_US UE_avoirdupois_hundredweight_US
#define CLEAN_UE_avoirdupois_hundredweight_Imperial UE_avoirdupois_hundredweight_Imperial
#define CLEAN_UE_avoirdupois_sack UE_avoirdupois_sack
#define CLEAN_UE_avoirdupois_kip UE_avoirdupois_kip
#define CLEAN_UE_avoirdupois_ton_US UE_avoirdupois_ton_US
#define CLEAN_UE_avoirdupois_ton_Imperial UE_avoirdupois_ton_Imperial
#define CLEAN_UE_tower_penny UE_tower_penny
#define CLEAN_UE_tower_pound UE_tower_pound
#define CLEAN_UE_trade_pound UE_trade_pound
#define CLEAN_UE_trade_stone UE_trade_stone
#define CLEAN_UE_troy_scruple UE_troy_scruple
#define CLEAN_UE_troy_pennyweight UE_troy_pennyweight
#define CLEAN_UE_troy_dram UE_troy_dram
#define CLEAN_UE_troy_ounce UE_troy_ounce
#define CLEAN_UE_troy_pound UE_troy_pound
#define CLEAN_UE_wool_pound UE_wool_pound
#define CLEAN_UE_wool_clove UE_wool_clove
#define CLEAN_UE_wool_stone UE_wool_stone
#define CLEAN_UE_wool_tod UE_wool_tod
#define CLEAN_UC_gram_liquid UC_gram_liquid
#define CLEAN_UC_kg_liquid UC_kg_liquid
#define CLEAN_UC_candela UC_candela
#define CLEAN_UC_lumen UC_lumen
#define CLEAN_UC_lux UC_lux
#define CLEAN_UC_kilo_lux UC_kilo_lux
#define CLEAN_UC_phot UC_phot
#define CLEAN_UC_stilb UC_stilb
#define CLEAN_UC_length UC_length
#define CLEAN_UC_meter UC_meter
#define CLEAN_UC_km UC_km
#define CLEAN_UC_m UC_m
#define CLEAN_UC_cm UC_cm
#define CLEAN_UC_mm UC_mm
#define CLEAN_UC_angstrom UC_angstrom
#define CLEAN_UC_fermi UC_fermi
#define CLEAN_UE_inch UE_inch
#define CLEAN_UE_nail UE_nail
#define CLEAN_UE_hand UE_hand
#define CLEAN_UE_link UE_link
#define CLEAN_UE_foot UE_foot
#define CLEAN_UE_yard UE_yard
#define CLEAN_UE_rod UE_rod
#define CLEAN_UE_pole UE_pole
#define CLEAN_UE_perch UE_perch
#define CLEAN_UE_lugg UE_lugg
#define CLEAN_UE_fathom UE_fathom
#define CLEAN_UE_chain UE_chain
#define CLEAN_UE_furlong UE_furlong
#define CLEAN_UE_statute_mile UE_statute_mile
#define CLEAN_UE_nautical_mile_modern UE_nautical_mile_modern
#define CLEAN_UE_nautical_mile UE_nautical_mile
#define CLEAN_UE_inch_length UE_inch_length
#define CLEAN_UE_nail_length UE_nail_length
#define CLEAN_UE_hand_length UE_hand_length
#define CLEAN_UE_link_length UE_link_length
#define CLEAN_UE_foot_length UE_foot_length
#define CLEAN_UE_yard_length UE_yard_length
#define CLEAN_UE_rod_length UE_rod_length
#define CLEAN_UE_pole_length UE_pole_length
#define CLEAN_UE_perch_length UE_perch_length
#define CLEAN_UE_lugg_length UE_lugg_length
#define CLEAN_UE_fathom_length UE_fathom_length
#define CLEAN_UE_chain_length UE_chain_length
#define CLEAN_UE_furlong_length UE_furlong_length
#define CLEAN_UE_statute_mile_length UE_statute_mile_length
#define CLEAN_UE_nautical_mile_modern_length UE_nautical_mile_modern_length
#define CLEAN_UE_nautical_mile_length UE_nautical_mile_length
#define CLEAN_UC_square_meter_flat_area_obs UC_square_meter_flat_area_obs
#define CLEAN_UC_square_meter_area UC_square_meter_area
#define CLEAN_UC_square_cm_area UC_square_cm_area
#define CLEAN_UC_are UC_are
#define CLEAN_UC_hectare UC_hectare
#define CLEAN_UE_acre UE_acre
#define CLEAN_UE_rood UE_rood
#define CLEAN_UE_arpent_area UE_arpent_area
#define CLEAN_UE_virgate UE_virgate
#define CLEAN_UE_hide UE_hide
#define CLEAN_UE_morgen_scandinavian UE_morgen_scandinavian
#define CLEAN_UE_morgen_prussian UE_morgen_prussian
#define CLEAN_UE_morgen_dutch UE_morgen_dutch
#define CLEAN_UE_morgen_south_african UE_morgen_south_african
#define CLEAN_UC_cubic_meter_volume UC_cubic_meter_volume
#define CLEAN_UC_liter UC_liter
#define CLEAN_UC_ml UC_ml
#define CLEAN_UE_minim UE_minim
#define CLEAN_UE_drachm UE_drachm
#define CLEAN_UE_ounce UE_ounce
#define CLEAN_UE_gill UE_gill
#define CLEAN_UE_mutchkin UE_mutchkin
#define CLEAN_UE_pint UE_pint
#define CLEAN_UE_fifth UE_fifth
#define CLEAN_UE_quart UE_quart
#define CLEAN_UE_gallon UE_gallon
#define CLEAN_UE_peck UE_peck
#define CLEAN_UE_bushel UE_bushel
#define CLEAN_UE_quarter UE_quarter
#define CLEAN_UE_tun UE_tun
#define CLEAN_UE_chaldron UE_chaldron
#define CLEAN_UE_fluid_minim_Imperial UE_fluid_minim_Imperial
#define CLEAN_UE_fluid_drachm_Imperial UE_fluid_drachm_Imperial
#define CLEAN_UE_fluid_ounce_Imperial UE_fluid_ounce_Imperial
#define CLEAN_UE_fluid_gill_Imperial UE_fluid_gill_Imperial
#define CLEAN_UE_fluid_mutchin_Imperial UE_fluid_mutchin_Imperial
#define CLEAN_UE_fluid_pint_Imperial UE_fluid_pint_Imperial
#define CLEAN_UE_fluid_fifth_Imperial UE_fluid_fifth_Imperial
#define CLEAN_UE_fluid_quart_Imperial UE_fluid_quart_Imperial
#define CLEAN_UE_fluid_gallon_Imperial UE_fluid_gallon_Imperial
#define CLEAN_UE_fluid_peck_Imperial UE_fluid_peck_Imperial
#define CLEAN_UE_fluid_bushel_Imperial UE_fluid_bushel_Imperial
#define CLEAN_UE_fluid_quarter_Imperial UE_fluid_quarter_Imperial
#define CLEAN_UE_fluid_tun_Imperial UE_fluid_tun_Imperial
#define CLEAN_UE_fluid_chaldron_Imperial UE_fluid_chaldron_Imperial
#define CLEAN_UE_fluid_firkin UE_fluid_firkin
#define CLEAN_UE_fluid_barrel UE_fluid_barrel
#define CLEAN_UE_fluid_hogshead UE_fluid_hogshead
#define CLEAN_UE_fluid_bottle UE_fluid_bottle
#define CLEAN_UE_fluid_minim_US UE_fluid_minim_US
#define CLEAN_UE_fluid_drachm_US UE_fluid_drachm_US
#define CLEAN_UE_fluid_ounce_US UE_fluid_ounce_US
#define CLEAN_UE_fluid_pint_US UE_fluid_pint_US
#define CLEAN_UE_fluid_gill_US UE_fluid_gill_US
#define CLEAN_UE_fluid_fifth_US UE_fluid_fifth_US
#define CLEAN_UE_fluid_quart_US UE_fluid_quart_US
#define CLEAN_UE_fluid_gallon_US UE_fluid_gallon_US
#define CLEAN_UE_fluid_peck_US UE_fluid_peck_US
#define CLEAN_UE_fluid_bushel_US UE_fluid_bushel_US
#define CLEAN_UE_fluid_quarter_US UE_fluid_quarter_US
#define CLEAN_UE_fluid_tun_US UE_fluid_tun_US
#define CLEAN_UE_fluid_chaldron_US UE_fluid_chaldron_US
#define CLEAN_UE_dry_minim_Imperial UE_dry_minim_Imperial
#define CLEAN_UE_dry_drachm_Imperial UE_dry_drachm_Imperial
#define CLEAN_UE_dry_ounce_Imperial UE_dry_ounce_Imperial
#define CLEAN_UE_dry_pint_Imperial UE_dry_pint_Imperial
#define CLEAN_UE_dry_gill_Imperial UE_dry_gill_Imperial
#define CLEAN_UE_dry_fifth_Imperial UE_dry_fifth_Imperial
#define CLEAN_UE_dry_quart_Imperial UE_dry_quart_Imperial
#define CLEAN_UE_dry_gallon_Imperial UE_dry_gallon_Imperial
#define CLEAN_UE_dry_peck_Imperial UE_dry_peck_Imperial
#define CLEAN_UE_dry_bushel_Imperial UE_dry_bushel_Imperial
#define CLEAN_UE_dry_quarter_Imperial UE_dry_quarter_Imperial
#define CLEAN_UE_dry_tun_Imperial UE_dry_tun_Imperial
#define CLEAN_UE_dry_chaldron_Imperial UE_dry_chaldron_Imperial
#define CLEAN_UE_dry_minimUS UE_dry_minimUS
#define CLEAN_UE_dry_drachm_US UE_dry_drachm_US
#define CLEAN_UE_dry_ounce_US UE_dry_ounce_US
#define CLEAN_UE_dry_pint_US UE_dry_pint_US
#define CLEAN_UE_dry_gill_US UE_dry_gill_US
#define CLEAN_UE_dry_fifth_US UE_dry_fifth_US
#define CLEAN_UE_dry_quart_US UE_dry_quart_US
#define CLEAN_UE_dry_gallon_US UE_dry_gallon_US
#define CLEAN_UE_dry_peck_US UE_dry_peck_US
#define CLEAN_UE_dry_bushel_US UE_dry_bushel_US
#define CLEAN_UE_dry_quarter_US UE_dry_quarter_US
#define CLEAN_UE_dry_tun_US UE_dry_tun_US
#define CLEAN_UE_dry_chaldron_US UE_dry_chaldron_US
#define CLEAN_UC_radian_angle UC_radian_angle
#define CLEAN_UC_degree_angle UC_degree_angle
#define CLEAN_UC_degrees_longitude UC_degrees_longitude
#define CLEAN_UC_degrees_latitutude UC_degrees_latitutude
#define CLEAN_UC_degree_from_east UC_degree_from_east
#define CLEAN_UC_degree_from_north UC_degree_from_north
#define CLEAN_UC_gradian_angle UC_gradian_angle
#define CLEAN_UC_gon UC_gon
#define CLEAN_UC_grade UC_grade
#define CLEAN_UC_steradian UC_steradian
#define CLEAN_UC_hertz UC_hertz
#define CLEAN_UC_fresnel UC_fresnel
#define CLEAN_UC_W_per_m_K_thermal_conductivity UC_W_per_m_K_thermal_conductivity
#define CLEAN_UC_joule_energy UC_joule_energy
#define CLEAN_UC_kilo_joule_energy UC_kilo_joule_energy
#define CLEAN_UC_mega_joule_energy UC_mega_joule_energy
#define CLEAN_UE_calorie_energy UE_calorie_energy
#define CLEAN_UE_mega_calorie_energy UE_mega_calorie_energy
#define CLEAN_UC_ergs UC_ergs
#define CLEAN_UC_watt_second UC_watt_second
#define CLEAN_UC_watt_hour UC_watt_hour
#define CLEAN_UC_watt_day UC_watt_day
#define CLEAN_UC_newton_force UC_newton_force
#define CLEAN_UC_newton UC_newton
#define CLEAN_UE_poundal UE_poundal
#define CLEAN_UC_watt_radiant_flux UC_watt_radiant_flux
#define CLEAN_UC_pascal_pressure UC_pascal_pressure
#define CLEAN_UC_kPa UC_kPa
#define CLEAN_UC_barye UC_barye
#define CLEAN_UE_bars_atmospheric_pressure UE_bars_atmospheric_pressure
#define CLEAN_UC_osmol UC_osmol
#define CLEAN_UC_pascal_second_dynamic_viscosity UC_pascal_second_dynamic_viscosity
#define CLEAN_UC_poise UC_poise
#define CLEAN_UC_m2_per_sec_kinematic_viscosity UC_m2_per_sec_kinematic_viscosity
#define CLEAN_UC_stock UC_stock
#define CLEAN_UC_ampere_current UC_ampere_current
#define CLEAN_UC_biot UC_biot
#define CLEAN_UC_faraday_charge UC_faraday_charge
#define CLEAN_UE_franklin UE_franklin
#define CLEAN_UC_volt_electric_potential UC_volt_electric_potential
#define CLEAN_UC_volt_electromotive_force_D UC_volt_electromotive_force_D
#define CLEAN_UC_farad UC_farad
#define CLEAN_UC_ohm UC_ohm
#define CLEAN_UC_siemens UC_siemens
#define CLEAN_UC_decisiemens UC_decisiemens
#define CLEAN_UC_mho UC_mho
#define CLEAN_UC_henry UC_henry
#define CLEAN_UC_maxwell UC_maxwell
#define CLEAN_UC_line UC_line
#define CLEAN_UC_weber UC_weber
#define CLEAN_UC_tesla UC_tesla
#define CLEAN_UC_gauss UC_gauss
#define CLEAN_UC_gamma UC_gamma
#define CLEAN_UC_becquerel UC_becquerel
#define CLEAN_UC_gray UC_gray
#define CLEAN_UC_sievert UC_sievert
#define CLEAN_UC_MJ_m2_solar_radiation UC_MJ_m2_solar_radiation
#define CLEAN_UC_nit UC_nit
#define CLEAN_UT_second UT_second
